/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "ovs_tunnel_network", schema = "cloud", uniqueConstraints = {
	@javax.persistence.UniqueConstraint(columnNames = {"from", "to", "network_id"})
})
public class OvsTunnelNetwork implements java.io.Serializable {

	private static final long serialVersionUID = -399420076;

	private java.lang.Long    id;
	private java.lang.Long    from;
	private java.lang.Long    to;
	private java.lang.Long    networkId;
	private java.lang.Integer key;
	private java.lang.String  portName;
	private java.lang.String  state;

	public OvsTunnelNetwork() {}

	public OvsTunnelNetwork(
		java.lang.Long    id,
		java.lang.Long    from,
		java.lang.Long    to,
		java.lang.Long    networkId,
		java.lang.Integer key,
		java.lang.String  portName,
		java.lang.String  state
	) {
		this.id = id;
		this.from = from;
		this.to = to;
		this.networkId = networkId;
		this.key = key;
		this.portName = portName;
		this.state = state;
	}

	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 20)
	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	@javax.persistence.Column(name = "from", nullable = false, precision = 20)
	public java.lang.Long getFrom() {
		return this.from;
	}

	public void setFrom(java.lang.Long from) {
		this.from = from;
	}

	@javax.persistence.Column(name = "to", nullable = false, precision = 20)
	public java.lang.Long getTo() {
		return this.to;
	}

	public void setTo(java.lang.Long to) {
		this.to = to;
	}

	@javax.persistence.Column(name = "network_id", nullable = false, precision = 20)
	public java.lang.Long getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(java.lang.Long networkId) {
		this.networkId = networkId;
	}

	@javax.persistence.Column(name = "key", precision = 10)
	public java.lang.Integer getKey() {
		return this.key;
	}

	public void setKey(java.lang.Integer key) {
		this.key = key;
	}

	@javax.persistence.Column(name = "port_name", length = 32)
	public java.lang.String getPortName() {
		return this.portName;
	}

	public void setPortName(java.lang.String portName) {
		this.portName = portName;
	}

	@javax.persistence.Column(name = "state", length = 16)
	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}
}
