/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "region", schema = "cloud")
public class Region implements java.io.Serializable {

	private static final long serialVersionUID = 1617460626;

	private java.lang.Integer id;
	private java.lang.String  name;
	private java.lang.String  endPoint;
	private java.lang.Byte    portableipServiceEnabled;
	private java.lang.Byte    gslbServiceEnabled;

	public Region() {}

	public Region(
		java.lang.Integer id,
		java.lang.String  name,
		java.lang.String  endPoint,
		java.lang.Byte    portableipServiceEnabled,
		java.lang.Byte    gslbServiceEnabled
	) {
		this.id = id;
		this.name = name;
		this.endPoint = endPoint;
		this.portableipServiceEnabled = portableipServiceEnabled;
		this.gslbServiceEnabled = gslbServiceEnabled;
	}

	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 10)
	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	@javax.persistence.Column(name = "name", unique = true, nullable = false, length = 255)
	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	@javax.persistence.Column(name = "end_point", nullable = false, length = 255)
	public java.lang.String getEndPoint() {
		return this.endPoint;
	}

	public void setEndPoint(java.lang.String endPoint) {
		this.endPoint = endPoint;
	}

	@javax.persistence.Column(name = "portableip_service_enabled", nullable = false, precision = 3)
	public java.lang.Byte getPortableipServiceEnabled() {
		return this.portableipServiceEnabled;
	}

	public void setPortableipServiceEnabled(java.lang.Byte portableipServiceEnabled) {
		this.portableipServiceEnabled = portableipServiceEnabled;
	}

	@javax.persistence.Column(name = "gslb_service_enabled", nullable = false, precision = 3)
	public java.lang.Byte getGslbServiceEnabled() {
		return this.gslbServiceEnabled;
	}

	public void setGslbServiceEnabled(java.lang.Byte gslbServiceEnabled) {
		this.gslbServiceEnabled = gslbServiceEnabled;
	}
}
