/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "system_vm", schema = "cloud")
public class SystemVm implements java.io.Serializable {

	private static final long serialVersionUID = 1188698584;

	private java.lang.Long   id;
	private java.lang.String role;

	public SystemVm() {}

	public SystemVm(
		java.lang.Long   id,
		java.lang.String role
	) {
		this.id = id;
		this.role = role;
	}

	@javax.persistence.Column(name = "id", nullable = false, precision = 19)
	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	@javax.persistence.Column(name = "role", nullable = false, length = 1024)
	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}
}
