/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in cloud
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table cloud.account
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Account ACCOUNT = org.apache.cloudstack.db.jooq.tables.Account.ACCOUNT;

	/**
	 * The table cloud.account_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AccountDetails ACCOUNT_DETAILS = org.apache.cloudstack.db.jooq.tables.AccountDetails.ACCOUNT_DETAILS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AccountNetstatsView ACCOUNT_NETSTATS_VIEW = org.apache.cloudstack.db.jooq.tables.AccountNetstatsView.ACCOUNT_NETSTATS_VIEW;

	/**
	 * The table cloud.account_network_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AccountNetworkRef ACCOUNT_NETWORK_REF = org.apache.cloudstack.db.jooq.tables.AccountNetworkRef.ACCOUNT_NETWORK_REF;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AccountView ACCOUNT_VIEW = org.apache.cloudstack.db.jooq.tables.AccountView.ACCOUNT_VIEW;

	/**
	 * The table cloud.account_vlan_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AccountVlanMap ACCOUNT_VLAN_MAP = org.apache.cloudstack.db.jooq.tables.AccountVlanMap.ACCOUNT_VLAN_MAP;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AccountVmstatsView ACCOUNT_VMSTATS_VIEW = org.apache.cloudstack.db.jooq.tables.AccountVmstatsView.ACCOUNT_VMSTATS_VIEW;

	/**
	 * The table cloud.account_vnet_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AccountVnetMap ACCOUNT_VNET_MAP = org.apache.cloudstack.db.jooq.tables.AccountVnetMap.ACCOUNT_VNET_MAP;

	/**
	 * The table cloud.affinity_group
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AffinityGroup AFFINITY_GROUP = org.apache.cloudstack.db.jooq.tables.AffinityGroup.AFFINITY_GROUP;

	/**
	 * The table cloud.affinity_group_domain_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AffinityGroupDomainMap AFFINITY_GROUP_DOMAIN_MAP = org.apache.cloudstack.db.jooq.tables.AffinityGroupDomainMap.AFFINITY_GROUP_DOMAIN_MAP;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AffinityGroupView AFFINITY_GROUP_VIEW = org.apache.cloudstack.db.jooq.tables.AffinityGroupView.AFFINITY_GROUP_VIEW;

	/**
	 * The table cloud.affinity_group_vm_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AffinityGroupVmMap AFFINITY_GROUP_VM_MAP = org.apache.cloudstack.db.jooq.tables.AffinityGroupVmMap.AFFINITY_GROUP_VM_MAP;

	/**
	 * The table cloud.alert
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Alert ALERT = org.apache.cloudstack.db.jooq.tables.Alert.ALERT;

	/**
	 * The table cloud.async_job
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AsyncJob ASYNC_JOB = org.apache.cloudstack.db.jooq.tables.AsyncJob.ASYNC_JOB;

	/**
	 * The table cloud.async_job_join_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AsyncJobJoinMap ASYNC_JOB_JOIN_MAP = org.apache.cloudstack.db.jooq.tables.AsyncJobJoinMap.ASYNC_JOB_JOIN_MAP;

	/**
	 * The table cloud.async_job_journal
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AsyncJobJournal ASYNC_JOB_JOURNAL = org.apache.cloudstack.db.jooq.tables.AsyncJobJournal.ASYNC_JOB_JOURNAL;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AsyncJobView ASYNC_JOB_VIEW = org.apache.cloudstack.db.jooq.tables.AsyncJobView.ASYNC_JOB_VIEW;

	/**
	 * The table cloud.autoscale_policies
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AutoscalePolicies AUTOSCALE_POLICIES = org.apache.cloudstack.db.jooq.tables.AutoscalePolicies.AUTOSCALE_POLICIES;

	/**
	 * The table cloud.autoscale_policy_condition_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AutoscalePolicyConditionMap AUTOSCALE_POLICY_CONDITION_MAP = org.apache.cloudstack.db.jooq.tables.AutoscalePolicyConditionMap.AUTOSCALE_POLICY_CONDITION_MAP;

	/**
	 * The table cloud.autoscale_vmgroups
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AutoscaleVmgroups AUTOSCALE_VMGROUPS = org.apache.cloudstack.db.jooq.tables.AutoscaleVmgroups.AUTOSCALE_VMGROUPS;

	/**
	 * The table cloud.autoscale_vmgroup_policy_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AutoscaleVmgroupPolicyMap AUTOSCALE_VMGROUP_POLICY_MAP = org.apache.cloudstack.db.jooq.tables.AutoscaleVmgroupPolicyMap.AUTOSCALE_VMGROUP_POLICY_MAP;

	/**
	 * The table cloud.autoscale_vmprofiles
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AutoscaleVmprofiles AUTOSCALE_VMPROFILES = org.apache.cloudstack.db.jooq.tables.AutoscaleVmprofiles.AUTOSCALE_VMPROFILES;

	/**
	 * The table cloud.baremetal_dhcp_devices
	 */
	public static final org.apache.cloudstack.db.jooq.tables.BaremetalDhcpDevices BAREMETAL_DHCP_DEVICES = org.apache.cloudstack.db.jooq.tables.BaremetalDhcpDevices.BAREMETAL_DHCP_DEVICES;

	/**
	 * The table cloud.baremetal_pxe_devices
	 */
	public static final org.apache.cloudstack.db.jooq.tables.BaremetalPxeDevices BAREMETAL_PXE_DEVICES = org.apache.cloudstack.db.jooq.tables.BaremetalPxeDevices.BAREMETAL_PXE_DEVICES;

	/**
	 * The table cloud.cluster
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Cluster CLUSTER = org.apache.cloudstack.db.jooq.tables.Cluster.CLUSTER;

	/**
	 * The table cloud.cluster_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ClusterDetails CLUSTER_DETAILS = org.apache.cloudstack.db.jooq.tables.ClusterDetails.CLUSTER_DETAILS;

	/**
	 * The table cloud.cluster_vsm_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ClusterVsmMap CLUSTER_VSM_MAP = org.apache.cloudstack.db.jooq.tables.ClusterVsmMap.CLUSTER_VSM_MAP;

	/**
	 * The table cloud.cmd_exec_log
	 */
	public static final org.apache.cloudstack.db.jooq.tables.CmdExecLog CMD_EXEC_LOG = org.apache.cloudstack.db.jooq.tables.CmdExecLog.CMD_EXEC_LOG;

	/**
	 * The table cloud.conditions
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Conditions CONDITIONS = org.apache.cloudstack.db.jooq.tables.Conditions.CONDITIONS;

	/**
	 * The table cloud.configuration
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Configuration CONFIGURATION = org.apache.cloudstack.db.jooq.tables.Configuration.CONFIGURATION;

	/**
	 * The table cloud.console_proxy
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ConsoleProxy CONSOLE_PROXY = org.apache.cloudstack.db.jooq.tables.ConsoleProxy.CONSOLE_PROXY;

	/**
	 * The table cloud.counter
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Counter COUNTER = org.apache.cloudstack.db.jooq.tables.Counter.COUNTER;

	/**
	 * The table cloud.data_center
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DataCenter DATA_CENTER = org.apache.cloudstack.db.jooq.tables.DataCenter.DATA_CENTER;

	/**
	 * The table cloud.data_center_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DataCenterDetails DATA_CENTER_DETAILS = org.apache.cloudstack.db.jooq.tables.DataCenterDetails.DATA_CENTER_DETAILS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DataCenterView DATA_CENTER_VIEW = org.apache.cloudstack.db.jooq.tables.DataCenterView.DATA_CENTER_VIEW;

	/**
	 * The table cloud.dc_storage_network_ip_range
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DcStorageNetworkIpRange DC_STORAGE_NETWORK_IP_RANGE = org.apache.cloudstack.db.jooq.tables.DcStorageNetworkIpRange.DC_STORAGE_NETWORK_IP_RANGE;

	/**
	 * The table cloud.dedicated_resources
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DedicatedResources DEDICATED_RESOURCES = org.apache.cloudstack.db.jooq.tables.DedicatedResources.DEDICATED_RESOURCES;

	/**
	 * The table cloud.disk_offering
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DiskOffering DISK_OFFERING = org.apache.cloudstack.db.jooq.tables.DiskOffering.DISK_OFFERING;

	/**
	 * The table cloud.disk_offering_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DiskOfferingDetails DISK_OFFERING_DETAILS = org.apache.cloudstack.db.jooq.tables.DiskOfferingDetails.DISK_OFFERING_DETAILS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DiskOfferingView DISK_OFFERING_VIEW = org.apache.cloudstack.db.jooq.tables.DiskOfferingView.DISK_OFFERING_VIEW;

	/**
	 * The table cloud.domain
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Domain DOMAIN = org.apache.cloudstack.db.jooq.tables.Domain.DOMAIN;

	/**
	 * The table cloud.domain_network_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DomainNetworkRef DOMAIN_NETWORK_REF = org.apache.cloudstack.db.jooq.tables.DomainNetworkRef.DOMAIN_NETWORK_REF;

	/**
	 * information about the domR instance
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DomainRouter DOMAIN_ROUTER = org.apache.cloudstack.db.jooq.tables.DomainRouter.DOMAIN_ROUTER;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.DomainRouterView DOMAIN_ROUTER_VIEW = org.apache.cloudstack.db.jooq.tables.DomainRouterView.DOMAIN_ROUTER_VIEW;

	/**
	 * The table cloud.elastic_lb_vm_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ElasticLbVmMap ELASTIC_LB_VM_MAP = org.apache.cloudstack.db.jooq.tables.ElasticLbVmMap.ELASTIC_LB_VM_MAP;

	/**
	 * The table cloud.event
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Event EVENT = org.apache.cloudstack.db.jooq.tables.Event.EVENT;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.EventView EVENT_VIEW = org.apache.cloudstack.db.jooq.tables.EventView.EVENT_VIEW;

	/**
	 * The table cloud.external_bigswitch_vns_devices
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalBigswitchVnsDevices EXTERNAL_BIGSWITCH_VNS_DEVICES = org.apache.cloudstack.db.jooq.tables.ExternalBigswitchVnsDevices.EXTERNAL_BIGSWITCH_VNS_DEVICES;

	/**
	 * The table cloud.external_cisco_asa1000v_devices
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalCiscoAsa1000vDevices EXTERNAL_CISCO_ASA1000V_DEVICES = org.apache.cloudstack.db.jooq.tables.ExternalCiscoAsa1000vDevices.EXTERNAL_CISCO_ASA1000V_DEVICES;

	/**
	 * The table cloud.external_cisco_vnmc_devices
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalCiscoVnmcDevices EXTERNAL_CISCO_VNMC_DEVICES = org.apache.cloudstack.db.jooq.tables.ExternalCiscoVnmcDevices.EXTERNAL_CISCO_VNMC_DEVICES;

	/**
	 * The table cloud.external_firewall_devices
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalFirewallDevices EXTERNAL_FIREWALL_DEVICES = org.apache.cloudstack.db.jooq.tables.ExternalFirewallDevices.EXTERNAL_FIREWALL_DEVICES;

	/**
	 * The table cloud.external_load_balancer_devices
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalLoadBalancerDevices EXTERNAL_LOAD_BALANCER_DEVICES = org.apache.cloudstack.db.jooq.tables.ExternalLoadBalancerDevices.EXTERNAL_LOAD_BALANCER_DEVICES;

	/**
	 * The table cloud.external_nicira_nvp_devices
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalNiciraNvpDevices EXTERNAL_NICIRA_NVP_DEVICES = org.apache.cloudstack.db.jooq.tables.ExternalNiciraNvpDevices.EXTERNAL_NICIRA_NVP_DEVICES;

	/**
	 * The table cloud.external_stratosphere_ssp_credentials
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalStratosphereSspCredentials EXTERNAL_STRATOSPHERE_SSP_CREDENTIALS = org.apache.cloudstack.db.jooq.tables.ExternalStratosphereSspCredentials.EXTERNAL_STRATOSPHERE_SSP_CREDENTIALS;

	/**
	 * The table cloud.external_stratosphere_ssp_tenants
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalStratosphereSspTenants EXTERNAL_STRATOSPHERE_SSP_TENANTS = org.apache.cloudstack.db.jooq.tables.ExternalStratosphereSspTenants.EXTERNAL_STRATOSPHERE_SSP_TENANTS;

	/**
	 * The table cloud.external_stratosphere_ssp_uuids
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalStratosphereSspUuids EXTERNAL_STRATOSPHERE_SSP_UUIDS = org.apache.cloudstack.db.jooq.tables.ExternalStratosphereSspUuids.EXTERNAL_STRATOSPHERE_SSP_UUIDS;

	/**
	 * The table cloud.firewall_rules
	 */
	public static final org.apache.cloudstack.db.jooq.tables.FirewallRules FIREWALL_RULES = org.apache.cloudstack.db.jooq.tables.FirewallRules.FIREWALL_RULES;

	/**
	 * The table cloud.firewall_rules_cidrs
	 */
	public static final org.apache.cloudstack.db.jooq.tables.FirewallRulesCidrs FIREWALL_RULES_CIDRS = org.apache.cloudstack.db.jooq.tables.FirewallRulesCidrs.FIREWALL_RULES_CIDRS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.FreeIpView FREE_IP_VIEW = org.apache.cloudstack.db.jooq.tables.FreeIpView.FREE_IP_VIEW;

	/**
	 * The table cloud.global_load_balancer_lb_rule_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.GlobalLoadBalancerLbRuleMap GLOBAL_LOAD_BALANCER_LB_RULE_MAP = org.apache.cloudstack.db.jooq.tables.GlobalLoadBalancerLbRuleMap.GLOBAL_LOAD_BALANCER_LB_RULE_MAP;

	/**
	 * The table cloud.global_load_balancing_rules
	 */
	public static final org.apache.cloudstack.db.jooq.tables.GlobalLoadBalancingRules GLOBAL_LOAD_BALANCING_RULES = org.apache.cloudstack.db.jooq.tables.GlobalLoadBalancingRules.GLOBAL_LOAD_BALANCING_RULES;

	/**
	 * The table cloud.guest_os
	 */
	public static final org.apache.cloudstack.db.jooq.tables.GuestOs GUEST_OS = org.apache.cloudstack.db.jooq.tables.GuestOs.GUEST_OS;

	/**
	 * The table cloud.guest_os_category
	 */
	public static final org.apache.cloudstack.db.jooq.tables.GuestOsCategory GUEST_OS_CATEGORY = org.apache.cloudstack.db.jooq.tables.GuestOsCategory.GUEST_OS_CATEGORY;

	/**
	 * The table cloud.guest_os_hypervisor
	 */
	public static final org.apache.cloudstack.db.jooq.tables.GuestOsHypervisor GUEST_OS_HYPERVISOR = org.apache.cloudstack.db.jooq.tables.GuestOsHypervisor.GUEST_OS_HYPERVISOR;

	/**
	 * The table cloud.host
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Host HOST = org.apache.cloudstack.db.jooq.tables.Host.HOST;

	/**
	 * The table cloud.host_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.HostDetails HOST_DETAILS = org.apache.cloudstack.db.jooq.tables.HostDetails.HOST_DETAILS;

	/**
	 * The table cloud.host_pod_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.HostPodRef HOST_POD_REF = org.apache.cloudstack.db.jooq.tables.HostPodRef.HOST_POD_REF;

	/**
	 * The table cloud.host_tags
	 */
	public static final org.apache.cloudstack.db.jooq.tables.HostTags HOST_TAGS = org.apache.cloudstack.db.jooq.tables.HostTags.HOST_TAGS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.HostView HOST_VIEW = org.apache.cloudstack.db.jooq.tables.HostView.HOST_VIEW;

	/**
	 * The table cloud.hypervisor_capabilities
	 */
	public static final org.apache.cloudstack.db.jooq.tables.HypervisorCapabilities HYPERVISOR_CAPABILITIES = org.apache.cloudstack.db.jooq.tables.HypervisorCapabilities.HYPERVISOR_CAPABILITIES;

	/**
	 * The table cloud.image_store
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ImageStore IMAGE_STORE = org.apache.cloudstack.db.jooq.tables.ImageStore.IMAGE_STORE;

	/**
	 * The table cloud.image_store_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ImageStoreDetails IMAGE_STORE_DETAILS = org.apache.cloudstack.db.jooq.tables.ImageStoreDetails.IMAGE_STORE_DETAILS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ImageStoreView IMAGE_STORE_VIEW = org.apache.cloudstack.db.jooq.tables.ImageStoreView.IMAGE_STORE_VIEW;

	/**
	 * The table cloud.inline_load_balancer_nic_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.InlineLoadBalancerNicMap INLINE_LOAD_BALANCER_NIC_MAP = org.apache.cloudstack.db.jooq.tables.InlineLoadBalancerNicMap.INLINE_LOAD_BALANCER_NIC_MAP;

	/**
	 * The table cloud.instance_group
	 */
	public static final org.apache.cloudstack.db.jooq.tables.InstanceGroup INSTANCE_GROUP = org.apache.cloudstack.db.jooq.tables.InstanceGroup.INSTANCE_GROUP;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.InstanceGroupView INSTANCE_GROUP_VIEW = org.apache.cloudstack.db.jooq.tables.InstanceGroupView.INSTANCE_GROUP_VIEW;

	/**
	 * The table cloud.instance_group_vm_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.InstanceGroupVmMap INSTANCE_GROUP_VM_MAP = org.apache.cloudstack.db.jooq.tables.InstanceGroupVmMap.INSTANCE_GROUP_VM_MAP;

	/**
	 * The table cloud.keystore
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Keystore KEYSTORE = org.apache.cloudstack.db.jooq.tables.Keystore.KEYSTORE;

	/**
	 * The table cloud.launch_permission
	 */
	public static final org.apache.cloudstack.db.jooq.tables.LaunchPermission LAUNCH_PERMISSION = org.apache.cloudstack.db.jooq.tables.LaunchPermission.LAUNCH_PERMISSION;

	/**
	 * The table cloud.ldap_configuration
	 */
	public static final org.apache.cloudstack.db.jooq.tables.LdapConfiguration LDAP_CONFIGURATION = org.apache.cloudstack.db.jooq.tables.LdapConfiguration.LDAP_CONFIGURATION;

	/**
	 * The table cloud.legacy_zones
	 */
	public static final org.apache.cloudstack.db.jooq.tables.LegacyZones LEGACY_ZONES = org.apache.cloudstack.db.jooq.tables.LegacyZones.LEGACY_ZONES;

	/**
	 * The table cloud.load_balancer_healthcheck_policies
	 */
	public static final org.apache.cloudstack.db.jooq.tables.LoadBalancerHealthcheckPolicies LOAD_BALANCER_HEALTHCHECK_POLICIES = org.apache.cloudstack.db.jooq.tables.LoadBalancerHealthcheckPolicies.LOAD_BALANCER_HEALTHCHECK_POLICIES;

	/**
	 * The table cloud.load_balancer_stickiness_policies
	 */
	public static final org.apache.cloudstack.db.jooq.tables.LoadBalancerStickinessPolicies LOAD_BALANCER_STICKINESS_POLICIES = org.apache.cloudstack.db.jooq.tables.LoadBalancerStickinessPolicies.LOAD_BALANCER_STICKINESS_POLICIES;

	/**
	 * The table cloud.load_balancer_vm_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.LoadBalancerVmMap LOAD_BALANCER_VM_MAP = org.apache.cloudstack.db.jooq.tables.LoadBalancerVmMap.LOAD_BALANCER_VM_MAP;

	/**
	 * The table cloud.load_balancing_rules
	 */
	public static final org.apache.cloudstack.db.jooq.tables.LoadBalancingRules LOAD_BALANCING_RULES = org.apache.cloudstack.db.jooq.tables.LoadBalancingRules.LOAD_BALANCING_RULES;

	/**
	 * The table cloud.mshost
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Mshost MSHOST = org.apache.cloudstack.db.jooq.tables.Mshost.MSHOST;

	/**
	 * The table cloud.mshost_peer
	 */
	public static final org.apache.cloudstack.db.jooq.tables.MshostPeer MSHOST_PEER = org.apache.cloudstack.db.jooq.tables.MshostPeer.MSHOST_PEER;

	/**
	 * The table cloud.netapp_lun
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetappLun NETAPP_LUN = org.apache.cloudstack.db.jooq.tables.NetappLun.NETAPP_LUN;

	/**
	 * The table cloud.netapp_pool
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetappPool NETAPP_POOL = org.apache.cloudstack.db.jooq.tables.NetappPool.NETAPP_POOL;

	/**
	 * The table cloud.netapp_volume
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetappVolume NETAPP_VOLUME = org.apache.cloudstack.db.jooq.tables.NetappVolume.NETAPP_VOLUME;

	/**
	 * The table cloud.netscaler_pod_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetscalerPodRef NETSCALER_POD_REF = org.apache.cloudstack.db.jooq.tables.NetscalerPodRef.NETSCALER_POD_REF;

	/**
	 * The table cloud.networks
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Networks NETWORKS = org.apache.cloudstack.db.jooq.tables.Networks.NETWORKS;

	/**
	 * The table cloud.network_acl
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkAcl NETWORK_ACL = org.apache.cloudstack.db.jooq.tables.NetworkAcl.NETWORK_ACL;

	/**
	 * The table cloud.network_acl_item
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkAclItem NETWORK_ACL_ITEM = org.apache.cloudstack.db.jooq.tables.NetworkAclItem.NETWORK_ACL_ITEM;

	/**
	 * The table cloud.network_asa1000v_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkAsa1000vMap NETWORK_ASA1000V_MAP = org.apache.cloudstack.db.jooq.tables.NetworkAsa1000vMap.NETWORK_ASA1000V_MAP;

	/**
	 * The table cloud.network_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkDetails NETWORK_DETAILS = org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS;

	/**
	 * The table cloud.network_external_firewall_device_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkExternalFirewallDeviceMap NETWORK_EXTERNAL_FIREWALL_DEVICE_MAP = org.apache.cloudstack.db.jooq.tables.NetworkExternalFirewallDeviceMap.NETWORK_EXTERNAL_FIREWALL_DEVICE_MAP;

	/**
	 * The table cloud.network_external_lb_device_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkExternalLbDeviceMap NETWORK_EXTERNAL_LB_DEVICE_MAP = org.apache.cloudstack.db.jooq.tables.NetworkExternalLbDeviceMap.NETWORK_EXTERNAL_LB_DEVICE_MAP;

	/**
	 * The table cloud.network_offerings
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkOfferings NETWORK_OFFERINGS = org.apache.cloudstack.db.jooq.tables.NetworkOfferings.NETWORK_OFFERINGS;

	/**
	 * The table cloud.network_offering_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkOfferingDetails NETWORK_OFFERING_DETAILS = org.apache.cloudstack.db.jooq.tables.NetworkOfferingDetails.NETWORK_OFFERING_DETAILS;

	/**
	 * The table cloud.network_rule_config
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkRuleConfig NETWORK_RULE_CONFIG = org.apache.cloudstack.db.jooq.tables.NetworkRuleConfig.NETWORK_RULE_CONFIG;

	/**
	 * The table cloud.nicira_nvp_nic_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NiciraNvpNicMap NICIRA_NVP_NIC_MAP = org.apache.cloudstack.db.jooq.tables.NiciraNvpNicMap.NICIRA_NVP_NIC_MAP;

	/**
	 * The table cloud.nicira_nvp_router_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NiciraNvpRouterMap NICIRA_NVP_ROUTER_MAP = org.apache.cloudstack.db.jooq.tables.NiciraNvpRouterMap.NICIRA_NVP_ROUTER_MAP;

	/**
	 * The table cloud.nics
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Nics NICS = org.apache.cloudstack.db.jooq.tables.Nics.NICS;

	/**
	 * The table cloud.nic_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NicDetails NIC_DETAILS = org.apache.cloudstack.db.jooq.tables.NicDetails.NIC_DETAILS;

	/**
	 * The table cloud.nic_ip_alias
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NicIpAlias NIC_IP_ALIAS = org.apache.cloudstack.db.jooq.tables.NicIpAlias.NIC_IP_ALIAS;

	/**
	 * The table cloud.nic_secondary_ips
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NicSecondaryIps NIC_SECONDARY_IPS = org.apache.cloudstack.db.jooq.tables.NicSecondaryIps.NIC_SECONDARY_IPS;

	/**
	 * The table cloud.ntwk_offering_service_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NtwkOfferingServiceMap NTWK_OFFERING_SERVICE_MAP = org.apache.cloudstack.db.jooq.tables.NtwkOfferingServiceMap.NTWK_OFFERING_SERVICE_MAP;

	/**
	 * The table cloud.ntwk_service_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NtwkServiceMap NTWK_SERVICE_MAP = org.apache.cloudstack.db.jooq.tables.NtwkServiceMap.NTWK_SERVICE_MAP;

	/**
	 * The table cloud.object_datastore_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ObjectDatastoreRef OBJECT_DATASTORE_REF = org.apache.cloudstack.db.jooq.tables.ObjectDatastoreRef.OBJECT_DATASTORE_REF;

	/**
	 * The table cloud.op_dc_ip_address_alloc
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpDcIpAddressAlloc OP_DC_IP_ADDRESS_ALLOC = org.apache.cloudstack.db.jooq.tables.OpDcIpAddressAlloc.OP_DC_IP_ADDRESS_ALLOC;

	/**
	 * The table cloud.op_dc_link_local_ip_address_alloc
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpDcLinkLocalIpAddressAlloc OP_DC_LINK_LOCAL_IP_ADDRESS_ALLOC = org.apache.cloudstack.db.jooq.tables.OpDcLinkLocalIpAddressAlloc.OP_DC_LINK_LOCAL_IP_ADDRESS_ALLOC;

	/**
	 * The table cloud.op_dc_storage_network_ip_address
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpDcStorageNetworkIpAddress OP_DC_STORAGE_NETWORK_IP_ADDRESS = org.apache.cloudstack.db.jooq.tables.OpDcStorageNetworkIpAddress.OP_DC_STORAGE_NETWORK_IP_ADDRESS;

	/**
	 * The table cloud.op_dc_vnet_alloc
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpDcVnetAlloc OP_DC_VNET_ALLOC = org.apache.cloudstack.db.jooq.tables.OpDcVnetAlloc.OP_DC_VNET_ALLOC;

	/**
	 * The table cloud.op_ha_work
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpHaWork OP_HA_WORK = org.apache.cloudstack.db.jooq.tables.OpHaWork.OP_HA_WORK;

	/**
	 * The table cloud.op_host
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpHost OP_HOST = org.apache.cloudstack.db.jooq.tables.OpHost.OP_HOST;

	/**
	 * The table cloud.op_host_capacity
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpHostCapacity OP_HOST_CAPACITY = org.apache.cloudstack.db.jooq.tables.OpHostCapacity.OP_HOST_CAPACITY;

	/**
	 * The table cloud.op_host_planner_reservation
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpHostPlannerReservation OP_HOST_PLANNER_RESERVATION = org.apache.cloudstack.db.jooq.tables.OpHostPlannerReservation.OP_HOST_PLANNER_RESERVATION;

	/**
	 * The table cloud.op_host_transfer
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpHostTransfer OP_HOST_TRANSFER = org.apache.cloudstack.db.jooq.tables.OpHostTransfer.OP_HOST_TRANSFER;

	/**
	 * The table cloud.op_host_upgrade
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpHostUpgrade OP_HOST_UPGRADE = org.apache.cloudstack.db.jooq.tables.OpHostUpgrade.OP_HOST_UPGRADE;

	/**
	 * The table cloud.op_it_work
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpItWork OP_IT_WORK = org.apache.cloudstack.db.jooq.tables.OpItWork.OP_IT_WORK;

	/**
	 * The table cloud.op_lock
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpLock OP_LOCK = org.apache.cloudstack.db.jooq.tables.OpLock.OP_LOCK;

	/**
	 * The table cloud.op_networks
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpNetworks OP_NETWORKS = org.apache.cloudstack.db.jooq.tables.OpNetworks.OP_NETWORKS;

	/**
	 * The table cloud.op_nwgrp_work
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpNwgrpWork OP_NWGRP_WORK = org.apache.cloudstack.db.jooq.tables.OpNwgrpWork.OP_NWGRP_WORK;

	/**
	 * The table cloud.op_pod_vlan_alloc
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpPodVlanAlloc OP_POD_VLAN_ALLOC = org.apache.cloudstack.db.jooq.tables.OpPodVlanAlloc.OP_POD_VLAN_ALLOC;

	/**
	 * The table cloud.op_user_stats_log
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpUserStatsLog OP_USER_STATS_LOG = org.apache.cloudstack.db.jooq.tables.OpUserStatsLog.OP_USER_STATS_LOG;

	/**
	 * The table cloud.op_vm_ruleset_log
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpVmRulesetLog OP_VM_RULESET_LOG = org.apache.cloudstack.db.jooq.tables.OpVmRulesetLog.OP_VM_RULESET_LOG;

	/**
	 * The table cloud.ovs_tunnel_interface
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OvsTunnelInterface OVS_TUNNEL_INTERFACE = org.apache.cloudstack.db.jooq.tables.OvsTunnelInterface.OVS_TUNNEL_INTERFACE;

	/**
	 * The table cloud.ovs_tunnel_network
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork OVS_TUNNEL_NETWORK = org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK;

	/**
	 * The table cloud.physical_network
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PhysicalNetwork PHYSICAL_NETWORK = org.apache.cloudstack.db.jooq.tables.PhysicalNetwork.PHYSICAL_NETWORK;

	/**
	 * The table cloud.physical_network_isolation_methods
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PhysicalNetworkIsolationMethods PHYSICAL_NETWORK_ISOLATION_METHODS = org.apache.cloudstack.db.jooq.tables.PhysicalNetworkIsolationMethods.PHYSICAL_NETWORK_ISOLATION_METHODS;

	/**
	 * The table cloud.physical_network_service_providers
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PhysicalNetworkServiceProviders PHYSICAL_NETWORK_SERVICE_PROVIDERS = org.apache.cloudstack.db.jooq.tables.PhysicalNetworkServiceProviders.PHYSICAL_NETWORK_SERVICE_PROVIDERS;

	/**
	 * The table cloud.physical_network_tags
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PhysicalNetworkTags PHYSICAL_NETWORK_TAGS = org.apache.cloudstack.db.jooq.tables.PhysicalNetworkTags.PHYSICAL_NETWORK_TAGS;

	/**
	 * The table cloud.physical_network_traffic_types
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PhysicalNetworkTrafficTypes PHYSICAL_NETWORK_TRAFFIC_TYPES = org.apache.cloudstack.db.jooq.tables.PhysicalNetworkTrafficTypes.PHYSICAL_NETWORK_TRAFFIC_TYPES;

	/**
	 * The table cloud.pod_vlan_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PodVlanMap POD_VLAN_MAP = org.apache.cloudstack.db.jooq.tables.PodVlanMap.POD_VLAN_MAP;

	/**
	 * The table cloud.portable_ip_address
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PortableIpAddress PORTABLE_IP_ADDRESS = org.apache.cloudstack.db.jooq.tables.PortableIpAddress.PORTABLE_IP_ADDRESS;

	/**
	 * The table cloud.portable_ip_range
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PortableIpRange PORTABLE_IP_RANGE = org.apache.cloudstack.db.jooq.tables.PortableIpRange.PORTABLE_IP_RANGE;

	/**
	 * The table cloud.port_forwarding_rules
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PortForwardingRules PORT_FORWARDING_RULES = org.apache.cloudstack.db.jooq.tables.PortForwardingRules.PORT_FORWARDING_RULES;

	/**
	 * The table cloud.port_profile
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PortProfile PORT_PROFILE = org.apache.cloudstack.db.jooq.tables.PortProfile.PORT_PROFILE;

	/**
	 * The table cloud.private_ip_address
	 */
	public static final org.apache.cloudstack.db.jooq.tables.PrivateIpAddress PRIVATE_IP_ADDRESS = org.apache.cloudstack.db.jooq.tables.PrivateIpAddress.PRIVATE_IP_ADDRESS;

	/**
	 * The table cloud.projects
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Projects PROJECTS = org.apache.cloudstack.db.jooq.tables.Projects.PROJECTS;

	/**
	 * The table cloud.project_account
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ProjectAccount PROJECT_ACCOUNT = org.apache.cloudstack.db.jooq.tables.ProjectAccount.PROJECT_ACCOUNT;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ProjectAccountView PROJECT_ACCOUNT_VIEW = org.apache.cloudstack.db.jooq.tables.ProjectAccountView.PROJECT_ACCOUNT_VIEW;

	/**
	 * The table cloud.project_invitations
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ProjectInvitations PROJECT_INVITATIONS = org.apache.cloudstack.db.jooq.tables.ProjectInvitations.PROJECT_INVITATIONS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ProjectInvitationView PROJECT_INVITATION_VIEW = org.apache.cloudstack.db.jooq.tables.ProjectInvitationView.PROJECT_INVITATION_VIEW;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ProjectView PROJECT_VIEW = org.apache.cloudstack.db.jooq.tables.ProjectView.PROJECT_VIEW;

	/**
	 * The table cloud.region
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Region REGION = org.apache.cloudstack.db.jooq.tables.Region.REGION;

	/**
	 * The table cloud.remote_access_vpn
	 */
	public static final org.apache.cloudstack.db.jooq.tables.RemoteAccessVpn REMOTE_ACCESS_VPN = org.apache.cloudstack.db.jooq.tables.RemoteAccessVpn.REMOTE_ACCESS_VPN;

	/**
	 * The table cloud.resource_count
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ResourceCount RESOURCE_COUNT = org.apache.cloudstack.db.jooq.tables.ResourceCount.RESOURCE_COUNT;

	/**
	 * The table cloud.resource_limit
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ResourceLimit RESOURCE_LIMIT = org.apache.cloudstack.db.jooq.tables.ResourceLimit.RESOURCE_LIMIT;

	/**
	 * The table cloud.resource_tags
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ResourceTags RESOURCE_TAGS = org.apache.cloudstack.db.jooq.tables.ResourceTags.RESOURCE_TAGS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ResourceTagView RESOURCE_TAG_VIEW = org.apache.cloudstack.db.jooq.tables.ResourceTagView.RESOURCE_TAG_VIEW;

	/**
	 * The table cloud.router_network_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.RouterNetworkRef ROUTER_NETWORK_REF = org.apache.cloudstack.db.jooq.tables.RouterNetworkRef.ROUTER_NETWORK_REF;

	/**
	 * The table cloud.s2s_customer_gateway
	 */
	public static final org.apache.cloudstack.db.jooq.tables.S2sCustomerGateway S2S_CUSTOMER_GATEWAY = org.apache.cloudstack.db.jooq.tables.S2sCustomerGateway.S2S_CUSTOMER_GATEWAY;

	/**
	 * The table cloud.s2s_vpn_connection
	 */
	public static final org.apache.cloudstack.db.jooq.tables.S2sVpnConnection S2S_VPN_CONNECTION = org.apache.cloudstack.db.jooq.tables.S2sVpnConnection.S2S_VPN_CONNECTION;

	/**
	 * The table cloud.s2s_vpn_gateway
	 */
	public static final org.apache.cloudstack.db.jooq.tables.S2sVpnGateway S2S_VPN_GATEWAY = org.apache.cloudstack.db.jooq.tables.S2sVpnGateway.S2S_VPN_GATEWAY;

	/**
	 * The table cloud.s3
	 */
	public static final org.apache.cloudstack.db.jooq.tables.S3 S3 = org.apache.cloudstack.db.jooq.tables.S3.S3;

	/**
	 * The table cloud.secondary_storage_vm
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SecondaryStorageVm SECONDARY_STORAGE_VM = org.apache.cloudstack.db.jooq.tables.SecondaryStorageVm.SECONDARY_STORAGE_VM;

	/**
	 * The table cloud.security_group
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SecurityGroup SECURITY_GROUP = org.apache.cloudstack.db.jooq.tables.SecurityGroup.SECURITY_GROUP;

	/**
	 * The table cloud.security_group_rule
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SecurityGroupRule SECURITY_GROUP_RULE = org.apache.cloudstack.db.jooq.tables.SecurityGroupRule.SECURITY_GROUP_RULE;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SecurityGroupView SECURITY_GROUP_VIEW = org.apache.cloudstack.db.jooq.tables.SecurityGroupView.SECURITY_GROUP_VIEW;

	/**
	 * The table cloud.security_group_vm_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SecurityGroupVmMap SECURITY_GROUP_VM_MAP = org.apache.cloudstack.db.jooq.tables.SecurityGroupVmMap.SECURITY_GROUP_VM_MAP;

	/**
	 * The table cloud.sequence
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Sequence SEQUENCE = org.apache.cloudstack.db.jooq.tables.Sequence.SEQUENCE;

	/**
	 * The table cloud.service_offering
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ServiceOffering SERVICE_OFFERING = org.apache.cloudstack.db.jooq.tables.ServiceOffering.SERVICE_OFFERING;

	/**
	 * The table cloud.service_offering_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ServiceOfferingDetails SERVICE_OFFERING_DETAILS = org.apache.cloudstack.db.jooq.tables.ServiceOfferingDetails.SERVICE_OFFERING_DETAILS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ServiceOfferingView SERVICE_OFFERING_VIEW = org.apache.cloudstack.db.jooq.tables.ServiceOfferingView.SERVICE_OFFERING_VIEW;

	/**
	 * The table cloud.snapshots
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Snapshots SNAPSHOTS = org.apache.cloudstack.db.jooq.tables.Snapshots.SNAPSHOTS;

	/**
	 * The table cloud.snapshot_policy
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SnapshotPolicy SNAPSHOT_POLICY = org.apache.cloudstack.db.jooq.tables.SnapshotPolicy.SNAPSHOT_POLICY;

	/**
	 * The table cloud.snapshot_schedule
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SnapshotSchedule SNAPSHOT_SCHEDULE = org.apache.cloudstack.db.jooq.tables.SnapshotSchedule.SNAPSHOT_SCHEDULE;

	/**
	 * The table cloud.snapshot_store_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SnapshotStoreRef SNAPSHOT_STORE_REF = org.apache.cloudstack.db.jooq.tables.SnapshotStoreRef.SNAPSHOT_STORE_REF;

	/**
	 * The table cloud.ssh_keypairs
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SshKeypairs SSH_KEYPAIRS = org.apache.cloudstack.db.jooq.tables.SshKeypairs.SSH_KEYPAIRS;

	/**
	 * The table cloud.stack_maid
	 */
	public static final org.apache.cloudstack.db.jooq.tables.StackMaid STACK_MAID = org.apache.cloudstack.db.jooq.tables.StackMaid.STACK_MAID;

	/**
	 * The table cloud.static_routes
	 */
	public static final org.apache.cloudstack.db.jooq.tables.StaticRoutes STATIC_ROUTES = org.apache.cloudstack.db.jooq.tables.StaticRoutes.STATIC_ROUTES;

	/**
	 * The table cloud.storage_pool
	 */
	public static final org.apache.cloudstack.db.jooq.tables.StoragePool STORAGE_POOL = org.apache.cloudstack.db.jooq.tables.StoragePool.STORAGE_POOL;

	/**
	 * The table cloud.storage_pool_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.StoragePoolDetails STORAGE_POOL_DETAILS = org.apache.cloudstack.db.jooq.tables.StoragePoolDetails.STORAGE_POOL_DETAILS;

	/**
	 * The table cloud.storage_pool_host_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.StoragePoolHostRef STORAGE_POOL_HOST_REF = org.apache.cloudstack.db.jooq.tables.StoragePoolHostRef.STORAGE_POOL_HOST_REF;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.StoragePoolView STORAGE_POOL_VIEW = org.apache.cloudstack.db.jooq.tables.StoragePoolView.STORAGE_POOL_VIEW;

	/**
	 * The table cloud.storage_pool_work
	 */
	public static final org.apache.cloudstack.db.jooq.tables.StoragePoolWork STORAGE_POOL_WORK = org.apache.cloudstack.db.jooq.tables.StoragePoolWork.STORAGE_POOL_WORK;

	/**
	 * The table cloud.swift
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Swift SWIFT = org.apache.cloudstack.db.jooq.tables.Swift.SWIFT;

	/**
	 * The table cloud.sync_queue
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SyncQueue SYNC_QUEUE = org.apache.cloudstack.db.jooq.tables.SyncQueue.SYNC_QUEUE;

	/**
	 * The table cloud.sync_queue_item
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SyncQueueItem SYNC_QUEUE_ITEM = org.apache.cloudstack.db.jooq.tables.SyncQueueItem.SYNC_QUEUE_ITEM;

	/**
	 * The table cloud.system_vm
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SystemVm SYSTEM_VM = org.apache.cloudstack.db.jooq.tables.SystemVm.SYSTEM_VM;

	/**
	 * The table cloud.template_host_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.TemplateHostRef TEMPLATE_HOST_REF = org.apache.cloudstack.db.jooq.tables.TemplateHostRef.TEMPLATE_HOST_REF;

	/**
	 * The table cloud.template_s3_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.TemplateS3Ref TEMPLATE_S3_REF = org.apache.cloudstack.db.jooq.tables.TemplateS3Ref.TEMPLATE_S3_REF;

	/**
	 * The table cloud.template_spool_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.TemplateSpoolRef TEMPLATE_SPOOL_REF = org.apache.cloudstack.db.jooq.tables.TemplateSpoolRef.TEMPLATE_SPOOL_REF;

	/**
	 * The table cloud.template_store_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.TemplateStoreRef TEMPLATE_STORE_REF = org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF;

	/**
	 * The table cloud.template_swift_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.TemplateSwiftRef TEMPLATE_SWIFT_REF = org.apache.cloudstack.db.jooq.tables.TemplateSwiftRef.TEMPLATE_SWIFT_REF;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.TemplateView TEMPLATE_VIEW = org.apache.cloudstack.db.jooq.tables.TemplateView.TEMPLATE_VIEW;

	/**
	 * The table cloud.template_zone_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.TemplateZoneRef TEMPLATE_ZONE_REF = org.apache.cloudstack.db.jooq.tables.TemplateZoneRef.TEMPLATE_ZONE_REF;

	/**
	 * The table cloud.ucs_blade
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UcsBlade UCS_BLADE = org.apache.cloudstack.db.jooq.tables.UcsBlade.UCS_BLADE;

	/**
	 * The table cloud.ucs_manager
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UcsManager UCS_MANAGER = org.apache.cloudstack.db.jooq.tables.UcsManager.UCS_MANAGER;

	/**
	 * The table cloud.upload
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Upload UPLOAD = org.apache.cloudstack.db.jooq.tables.Upload.UPLOAD;

	/**
	 * The table cloud.usage_event
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UsageEvent USAGE_EVENT = org.apache.cloudstack.db.jooq.tables.UsageEvent.USAGE_EVENT;

	/**
	 * The table cloud.user
	 */
	public static final org.apache.cloudstack.db.jooq.tables.User USER = org.apache.cloudstack.db.jooq.tables.User.USER;

	/**
	 * The table cloud.user_ipv6_address
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UserIpv6Address USER_IPV6_ADDRESS = org.apache.cloudstack.db.jooq.tables.UserIpv6Address.USER_IPV6_ADDRESS;

	/**
	 * The table cloud.user_ip_address
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UserIpAddress USER_IP_ADDRESS = org.apache.cloudstack.db.jooq.tables.UserIpAddress.USER_IP_ADDRESS;

	/**
	 * The table cloud.user_statistics
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UserStatistics USER_STATISTICS = org.apache.cloudstack.db.jooq.tables.UserStatistics.USER_STATISTICS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UserView USER_VIEW = org.apache.cloudstack.db.jooq.tables.UserView.USER_VIEW;

	/**
	 * The table cloud.user_vm
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UserVm USER_VM = org.apache.cloudstack.db.jooq.tables.UserVm.USER_VM;

	/**
	 * The table cloud.user_vm_clone_setting
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UserVmCloneSetting USER_VM_CLONE_SETTING = org.apache.cloudstack.db.jooq.tables.UserVmCloneSetting.USER_VM_CLONE_SETTING;

	/**
	 * The table cloud.user_vm_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UserVmDetails USER_VM_DETAILS = org.apache.cloudstack.db.jooq.tables.UserVmDetails.USER_VM_DETAILS;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UserVmView USER_VM_VIEW = org.apache.cloudstack.db.jooq.tables.UserVmView.USER_VM_VIEW;

	/**
	 * The table cloud.version
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Version VERSION = org.apache.cloudstack.db.jooq.tables.Version.VERSION;

	/**
	 * The table cloud.virtual_router_providers
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VirtualRouterProviders VIRTUAL_ROUTER_PROVIDERS = org.apache.cloudstack.db.jooq.tables.VirtualRouterProviders.VIRTUAL_ROUTER_PROVIDERS;

	/**
	 * The table cloud.virtual_supervisor_module
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VirtualSupervisorModule VIRTUAL_SUPERVISOR_MODULE = org.apache.cloudstack.db.jooq.tables.VirtualSupervisorModule.VIRTUAL_SUPERVISOR_MODULE;

	/**
	 * The table cloud.vlan
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Vlan VLAN = org.apache.cloudstack.db.jooq.tables.Vlan.VLAN;

	/**
	 * The table cloud.vmware_data_center
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmwareDataCenter VMWARE_DATA_CENTER = org.apache.cloudstack.db.jooq.tables.VmwareDataCenter.VMWARE_DATA_CENTER;

	/**
	 * The table cloud.vmware_data_center_zone_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmwareDataCenterZoneMap VMWARE_DATA_CENTER_ZONE_MAP = org.apache.cloudstack.db.jooq.tables.VmwareDataCenterZoneMap.VMWARE_DATA_CENTER_ZONE_MAP;

	/**
	 * The table cloud.vm_compute_tags
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmComputeTags VM_COMPUTE_TAGS = org.apache.cloudstack.db.jooq.tables.VmComputeTags.VM_COMPUTE_TAGS;

	/**
	 * The table cloud.vm_disk_statistics
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmDiskStatistics VM_DISK_STATISTICS = org.apache.cloudstack.db.jooq.tables.VmDiskStatistics.VM_DISK_STATISTICS;

	/**
	 * The table cloud.vm_instance
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmInstance VM_INSTANCE = org.apache.cloudstack.db.jooq.tables.VmInstance.VM_INSTANCE;

	/**
	 * The table cloud.vm_network_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmNetworkMap VM_NETWORK_MAP = org.apache.cloudstack.db.jooq.tables.VmNetworkMap.VM_NETWORK_MAP;

	/**
	 * The table cloud.vm_reservation
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmReservation VM_RESERVATION = org.apache.cloudstack.db.jooq.tables.VmReservation.VM_RESERVATION;

	/**
	 * The table cloud.vm_root_disk_tags
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmRootDiskTags VM_ROOT_DISK_TAGS = org.apache.cloudstack.db.jooq.tables.VmRootDiskTags.VM_ROOT_DISK_TAGS;

	/**
	 * The table cloud.vm_snapshots
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmSnapshots VM_SNAPSHOTS = org.apache.cloudstack.db.jooq.tables.VmSnapshots.VM_SNAPSHOTS;

	/**
	 * The table cloud.vm_template
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmTemplate VM_TEMPLATE = org.apache.cloudstack.db.jooq.tables.VmTemplate.VM_TEMPLATE;

	/**
	 * The table cloud.vm_template_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmTemplateDetails VM_TEMPLATE_DETAILS = org.apache.cloudstack.db.jooq.tables.VmTemplateDetails.VM_TEMPLATE_DETAILS;

	/**
	 * The table cloud.vm_work_job
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmWorkJob VM_WORK_JOB = org.apache.cloudstack.db.jooq.tables.VmWorkJob.VM_WORK_JOB;

	/**
	 * The table cloud.volumes
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Volumes VOLUMES = org.apache.cloudstack.db.jooq.tables.Volumes.VOLUMES;

	/**
	 * The table cloud.volume_details
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VolumeDetails VOLUME_DETAILS = org.apache.cloudstack.db.jooq.tables.VolumeDetails.VOLUME_DETAILS;

	/**
	 * The table cloud.volume_host_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VolumeHostRef VOLUME_HOST_REF = org.apache.cloudstack.db.jooq.tables.VolumeHostRef.VOLUME_HOST_REF;

	/**
	 * The table cloud.volume_reservation
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VolumeReservation VOLUME_RESERVATION = org.apache.cloudstack.db.jooq.tables.VolumeReservation.VOLUME_RESERVATION;

	/**
	 * The table cloud.volume_store_ref
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VolumeStoreRef VOLUME_STORE_REF = org.apache.cloudstack.db.jooq.tables.VolumeStoreRef.VOLUME_STORE_REF;

	/**
	 * VIEW
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VolumeView VOLUME_VIEW = org.apache.cloudstack.db.jooq.tables.VolumeView.VOLUME_VIEW;

	/**
	 * The table cloud.vpc
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Vpc VPC = org.apache.cloudstack.db.jooq.tables.Vpc.VPC;

	/**
	 * The table cloud.vpc_gateways
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VpcGateways VPC_GATEWAYS = org.apache.cloudstack.db.jooq.tables.VpcGateways.VPC_GATEWAYS;

	/**
	 * The table cloud.vpc_offerings
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VpcOfferings VPC_OFFERINGS = org.apache.cloudstack.db.jooq.tables.VpcOfferings.VPC_OFFERINGS;

	/**
	 * The table cloud.vpc_offering_service_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VpcOfferingServiceMap VPC_OFFERING_SERVICE_MAP = org.apache.cloudstack.db.jooq.tables.VpcOfferingServiceMap.VPC_OFFERING_SERVICE_MAP;

	/**
	 * The table cloud.vpc_service_map
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VpcServiceMap VPC_SERVICE_MAP = org.apache.cloudstack.db.jooq.tables.VpcServiceMap.VPC_SERVICE_MAP;

	/**
	 * The table cloud.vpn_users
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VpnUsers VPN_USERS = org.apache.cloudstack.db.jooq.tables.VpnUsers.VPN_USERS;
}
