/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountVnetMap extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord> {

	private static final long serialVersionUID = 687340592;

	/**
	 * The singleton instance of <code>cloud.account_vnet_map</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AccountVnetMap ACCOUNT_VNET_MAP = new org.apache.cloudstack.db.jooq.tables.AccountVnetMap();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord.class;
	}

	/**
	 * The column <code>cloud.account_vnet_map.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.account_vnet_map.uuid</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cloud.account_vnet_map.vnet_range</code>. dedicated guest vlan range
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord, java.lang.String> VNET_RANGE = createField("vnet_range", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.account_vnet_map.account_id</code>. account id. foreign key to account table
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.account_vnet_map.physical_network_id</code>. physical network id. foreign key to the the physical network table
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord, java.lang.Long> PHYSICAL_NETWORK_ID = createField("physical_network_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * Create a <code>cloud.account_vnet_map</code> table reference
	 */
	public AccountVnetMap() {
		super("account_vnet_map", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.account_vnet_map</code> table reference
	 */
	public AccountVnetMap(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.AccountVnetMap.ACCOUNT_VNET_MAP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_ACCOUNT_VNET_MAP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_ACCOUNT_VNET_MAP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_ACCOUNT_VNET_MAP_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_ACCOUNT_VNET_MAP_ID, org.apache.cloudstack.db.jooq.Keys.KEY_ACCOUNT_VNET_MAP_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.AccountVnetMapRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_ACCOUNT_VNET_MAP__ACCOUNT_ID, org.apache.cloudstack.db.jooq.Keys.FK_ACCOUNT_VNET_MAP__PHYSICAL_NETWORK_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.AccountVnetMap as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.AccountVnetMap(alias);
	}
}
