/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountNetworkRef extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord> {

	private static final long serialVersionUID = -1881389437;

	/**
	 * The singleton instance of <code>cloud.account_network_ref</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.AccountNetworkRef ACCOUNT_NETWORK_REF = new org.apache.cloudstack.db.jooq.tables.AccountNetworkRef();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord.class;
	}

	/**
	 * The column <code>cloud.account_network_ref.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.account_network_ref.account_id</code>. account id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.account_network_ref.network_id</code>. network id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord, java.lang.Long> NETWORK_ID = createField("network_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.account_network_ref.is_owner</code>. is the owner of the network
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord, java.lang.Short> IS_OWNER = createField("is_owner", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this);

	/**
	 * Create a <code>cloud.account_network_ref</code> table reference
	 */
	public AccountNetworkRef() {
		super("account_network_ref", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.account_network_ref</code> table reference
	 */
	public AccountNetworkRef(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.AccountNetworkRef.ACCOUNT_NETWORK_REF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_ACCOUNT_NETWORK_REF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_ACCOUNT_NETWORK_REF_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_ACCOUNT_NETWORK_REF_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.AccountNetworkRefRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_ACCOUNT_NETWORK_REF__ACCOUNT_ID, org.apache.cloudstack.db.jooq.Keys.FK_ACCOUNT_NETWORK_REF__NETWORKS_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.AccountNetworkRef as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.AccountNetworkRef(alias);
	}
}
