/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alert extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.AlertRecord> {

	private static final long serialVersionUID = -1781250292;

	/**
	 * The singleton instance of <code>cloud.alert</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Alert ALERT = new org.apache.cloudstack.db.jooq.tables.Alert();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.AlertRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.AlertRecord.class;
	}

	/**
	 * The column <code>cloud.alert.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.alert.uuid</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>cloud.alert.type</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>cloud.alert.cluster_id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.Long> CLUSTER_ID = createField("cluster_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.alert.pod_id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.Long> POD_ID = createField("pod_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.alert.data_center_id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.Long> DATA_CENTER_ID = createField("data_center_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.alert.subject</code>. according to SMTP spec, max subject length is 1000 including the CRLF character, so allow enough space to fit long pod/zone/host names
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.VARCHAR.length(999), this);

	/**
	 * The column <code>cloud.alert.sent_count</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.Integer> SENT_COUNT = createField("sent_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>cloud.alert.created</code>. when this alert type was created
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.alert.last_sent</code>. Last time the alert was sent
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.sql.Timestamp> LAST_SENT = createField("last_sent", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.alert.resolved</code>. when the alert status was resolved (available memory no longer at critical level, etc.)
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.sql.Timestamp> RESOLVED = createField("resolved", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.alert.archived</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.Byte> ARCHIVED = createField("archived", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this);

	/**
	 * Create a <code>cloud.alert</code> table reference
	 */
	public Alert() {
		super("alert", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.alert</code> table reference
	 */
	public Alert(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.Alert.ALERT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.AlertRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_ALERT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.AlertRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_ALERT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.AlertRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.AlertRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_ALERT_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_ALERT_UC_ALERT__UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.Alert as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.Alert(alias);
	}
}
