/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BaremetalPxeDevices extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord> {

	private static final long serialVersionUID = 926175844;

	/**
	 * The singleton instance of <code>cloud.baremetal_pxe_devices</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.BaremetalPxeDevices BAREMETAL_PXE_DEVICES = new org.apache.cloudstack.db.jooq.tables.BaremetalPxeDevices();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord.class;
	}

	/**
	 * The column <code>cloud.baremetal_pxe_devices.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.baremetal_pxe_devices.uuid</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>cloud.baremetal_pxe_devices.nsp_id</code>. Network Service Provider ID
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, java.lang.Long> NSP_ID = createField("nsp_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.baremetal_pxe_devices.pod_id</code>. Pod id where this pxe server in, for pxe per zone this field is null
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, java.lang.Long> POD_ID = createField("pod_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.baremetal_pxe_devices.device_type</code>. type of the pxe device
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, java.lang.String> DEVICE_TYPE = createField("device_type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cloud.baremetal_pxe_devices.physical_network_id</code>. id of the physical network in to which external pxe device is added
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, java.lang.Long> PHYSICAL_NETWORK_ID = createField("physical_network_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.baremetal_pxe_devices.host_id</code>. host id coresponding to the external pxe device
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, java.lang.Long> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>cloud.baremetal_pxe_devices</code> table reference
	 */
	public BaremetalPxeDevices() {
		super("baremetal_pxe_devices", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.baremetal_pxe_devices</code> table reference
	 */
	public BaremetalPxeDevices(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.BaremetalPxeDevices.BAREMETAL_PXE_DEVICES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_BAREMETAL_PXE_DEVICES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_BAREMETAL_PXE_DEVICES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_BAREMETAL_PXE_DEVICES_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_BAREMETAL_PXE_DEVICES_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.BaremetalPxeDevicesRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_EXTERNAL_PXE_DEVICES_NSP_ID, org.apache.cloudstack.db.jooq.Keys.FK_EXTERNAL_PXE_DEVICES_PHYSICAL_NETWORK_ID, org.apache.cloudstack.db.jooq.Keys.FK_EXTERNAL_PXE_DEVICES_HOST_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.BaremetalPxeDevices as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.BaremetalPxeDevices(alias);
	}
}
