/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmdExecLog extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord> {

	private static final long serialVersionUID = -992069656;

	/**
	 * The singleton instance of <code>cloud.cmd_exec_log</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.CmdExecLog CMD_EXEC_LOG = new org.apache.cloudstack.db.jooq.tables.CmdExecLog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord.class;
	}

	/**
	 * The column <code>cloud.cmd_exec_log.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.cmd_exec_log.host_id</code>. host id of the system VM agent that command is sent to
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord, java.lang.Long> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.cmd_exec_log.instance_id</code>. instance id of the system VM that command is executed on
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord, java.lang.Long> INSTANCE_ID = createField("instance_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.cmd_exec_log.command_name</code>. command name
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord, java.lang.String> COMMAND_NAME = createField("command_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.cmd_exec_log.weight</code>. command weight in consideration of the load factor added to host that is executing the command
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord, java.lang.Integer> WEIGHT = createField("weight", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>cloud.cmd_exec_log.created</code>. date created
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * Create a <code>cloud.cmd_exec_log</code> table reference
	 */
	public CmdExecLog() {
		super("cmd_exec_log", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.cmd_exec_log</code> table reference
	 */
	public CmdExecLog(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.CmdExecLog.CMD_EXEC_LOG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_CMD_EXEC_LOG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_CMD_EXEC_LOG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_CMD_EXEC_LOG_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.CmdExecLogRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_CMD_EXEC_LOG_REF__INST_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.CmdExecLog as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.CmdExecLog(alias);
	}
}
