/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Configuration extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord> {

	private static final long serialVersionUID = -734737783;

	/**
	 * The singleton instance of <code>cloud.configuration</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.Configuration CONFIGURATION = new org.apache.cloudstack.db.jooq.tables.Configuration();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord.class;
	}

	/**
	 * The column <code>cloud.configuration.category</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.lang.String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaulted(true), this);

	/**
	 * The column <code>cloud.configuration.instance</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.lang.String> INSTANCE = createField("instance", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.configuration.component</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.lang.String> COMPONENT = createField("component", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaulted(true), this);

	/**
	 * The column <code>cloud.configuration.name</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.configuration.value</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(4095), this);

	/**
	 * The column <code>cloud.configuration.description</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this);

	/**
	 * The column <code>cloud.configuration.default_value</code>. Default value for a configuration parameter
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.lang.String> DEFAULT_VALUE = createField("default_value", org.jooq.impl.SQLDataType.VARCHAR.length(4095), this);

	/**
	 * The column <code>cloud.configuration.updated</code>. Time this was updated by the server. null means this row is obsolete.
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.configuration.scope</code>. Can this parameter be scoped
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.lang.String> SCOPE = createField("scope", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cloud.configuration.is_dynamic</code>. Can the parameter be change dynamically without restarting the server
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord, java.lang.Byte> IS_DYNAMIC = createField("is_dynamic", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this);

	/**
	 * Create a <code>cloud.configuration</code> table reference
	 */
	public Configuration() {
		super("configuration", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.configuration</code> table reference
	 */
	public Configuration(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.Configuration.CONFIGURATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_CONFIGURATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.ConfigurationRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_CONFIGURATION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.Configuration as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.Configuration(alias);
	}
}
