/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExternalCiscoVnmcDevices extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord> {

	private static final long serialVersionUID = 619305078;

	/**
	 * The singleton instance of <code>cloud.external_cisco_vnmc_devices</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ExternalCiscoVnmcDevices EXTERNAL_CISCO_VNMC_DEVICES = new org.apache.cloudstack.db.jooq.tables.ExternalCiscoVnmcDevices();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord.class;
	}

	/**
	 * The column <code>cloud.external_cisco_vnmc_devices.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.external_cisco_vnmc_devices.uuid</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cloud.external_cisco_vnmc_devices.physical_network_id</code>. id of the physical network in to which cisco vnmc device is added
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord, java.lang.Long> PHYSICAL_NETWORK_ID = createField("physical_network_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.external_cisco_vnmc_devices.provider_name</code>. Service Provider name corresponding to this cisco vnmc device
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord, java.lang.String> PROVIDER_NAME = createField("provider_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.external_cisco_vnmc_devices.device_name</code>. name of the cisco vnmc device
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord, java.lang.String> DEVICE_NAME = createField("device_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.external_cisco_vnmc_devices.host_id</code>. host id coresponding to the external cisco vnmc device
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord, java.lang.Long> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * Create a <code>cloud.external_cisco_vnmc_devices</code> table reference
	 */
	public ExternalCiscoVnmcDevices() {
		super("external_cisco_vnmc_devices", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.external_cisco_vnmc_devices</code> table reference
	 */
	public ExternalCiscoVnmcDevices(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.ExternalCiscoVnmcDevices.EXTERNAL_CISCO_VNMC_DEVICES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_EXTERNAL_CISCO_VNMC_DEVICES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_EXTERNAL_CISCO_VNMC_DEVICES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_EXTERNAL_CISCO_VNMC_DEVICES_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_EXTERNAL_CISCO_VNMC_DEVICES_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.ExternalCiscoVnmcDevicesRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_EXTERNAL_CISCO_VNMC_DEVICES__PHYSICAL_NETWORK_ID, org.apache.cloudstack.db.jooq.Keys.FK_EXTERNAL_CISCO_VNMC_DEVICES__HOST_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.ExternalCiscoVnmcDevices as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.ExternalCiscoVnmcDevices(alias);
	}
}
