/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostTags extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord> {

	private static final long serialVersionUID = -1184809723;

	/**
	 * The singleton instance of <code>cloud.host_tags</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.HostTags HOST_TAGS = new org.apache.cloudstack.db.jooq.tables.HostTags();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord.class;
	}

	/**
	 * The column <code>cloud.host_tags.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.host_tags.host_id</code>. host id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord, java.lang.Long> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.host_tags.tag</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord, java.lang.String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * Create a <code>cloud.host_tags</code> table reference
	 */
	public HostTags() {
		super("host_tags", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.host_tags</code> table reference
	 */
	public HostTags(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.HostTags.HOST_TAGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_HOST_TAGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_HOST_TAGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_HOST_TAGS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.HostTagsRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_HOST_TAGS__HOST_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.HostTags as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.HostTags(alias);
	}
}
