/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostDetails extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord> {

	private static final long serialVersionUID = -1081809703;

	/**
	 * The singleton instance of <code>cloud.host_details</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.HostDetails HOST_DETAILS = new org.apache.cloudstack.db.jooq.tables.HostDetails();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord.class;
	}

	/**
	 * The column <code>cloud.host_details.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.host_details.host_id</code>. host id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord, java.lang.Long> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.host_details.name</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.host_details.value</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * Create a <code>cloud.host_details</code> table reference
	 */
	public HostDetails() {
		super("host_details", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.host_details</code> table reference
	 */
	public HostDetails(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.HostDetails.HOST_DETAILS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_HOST_DETAILS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_HOST_DETAILS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_HOST_DETAILS_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_HOST_DETAILS_UK_HOST_ID_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.HostDetailsRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_HOST_DETAILS__HOST_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.HostDetails as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.HostDetails(alias);
	}
}
