/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LegacyZones extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord> {

	private static final long serialVersionUID = -1595533983;

	/**
	 * The singleton instance of <code>cloud.legacy_zones</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.LegacyZones LEGACY_ZONES = new org.apache.cloudstack.db.jooq.tables.LegacyZones();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord.class;
	}

	/**
	 * The column <code>cloud.legacy_zones.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.legacy_zones.zone_id</code>. id of CloudStack zone
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord, java.lang.Long> ZONE_ID = createField("zone_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * Create a <code>cloud.legacy_zones</code> table reference
	 */
	public LegacyZones() {
		super("legacy_zones", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.legacy_zones</code> table reference
	 */
	public LegacyZones(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.LegacyZones.LEGACY_ZONES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_LEGACY_ZONES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_LEGACY_ZONES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_LEGACY_ZONES_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_LEGACY_ZONES_ZONE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.LegacyZonesRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_LEGACY_ZONES__ZONE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.LegacyZones as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.LegacyZones(alias);
	}
}
