/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetappPool extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord> {

	private static final long serialVersionUID = -221516222;

	/**
	 * The singleton instance of <code>cloud.netapp_pool</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetappPool NETAPP_POOL = new org.apache.cloudstack.db.jooq.tables.NetappPool();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord.class;
	}

	/**
	 * The column <code>cloud.netapp_pool.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.netapp_pool.name</code>. name for the pool
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.netapp_pool.algorithm</code>. algorithm
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord, java.lang.String> ALGORITHM = createField("algorithm", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * Create a <code>cloud.netapp_pool</code> table reference
	 */
	public NetappPool() {
		super("netapp_pool", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.netapp_pool</code> table reference
	 */
	public NetappPool(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.NetappPool.NETAPP_POOL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_NETAPP_POOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_NETAPP_POOL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NetappPoolRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_NETAPP_POOL_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_NETAPP_POOL_ID, org.apache.cloudstack.db.jooq.Keys.KEY_NETAPP_POOL_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.NetappPool as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.NetappPool(alias);
	}
}
