/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetappLun extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord> {

	private static final long serialVersionUID = -559822816;

	/**
	 * The singleton instance of <code>cloud.netapp_lun</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetappLun NETAPP_LUN = new org.apache.cloudstack.db.jooq.tables.NetappLun();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord.class;
	}

	/**
	 * The column <code>cloud.netapp_lun.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.netapp_lun.lun_name</code>. lun name
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord, java.lang.String> LUN_NAME = createField("lun_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.netapp_lun.target_iqn</code>. target iqn
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord, java.lang.String> TARGET_IQN = createField("target_iqn", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.netapp_lun.path</code>. lun path
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord, java.lang.String> PATH = createField("path", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.netapp_lun.size</code>. lun size
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord, java.lang.Long> SIZE = createField("size", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.netapp_lun.volume_id</code>. parent volume id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord, java.lang.Long> VOLUME_ID = createField("volume_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * Create a <code>cloud.netapp_lun</code> table reference
	 */
	public NetappLun() {
		super("netapp_lun", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.netapp_lun</code> table reference
	 */
	public NetappLun(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.NetappLun.NETAPP_LUN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_NETAPP_LUN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_NETAPP_LUN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_NETAPP_LUN_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_NETAPP_LUN_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.NetappLunRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_NETAPP_LUN__VOLUME_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.NetappLun as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.NetappLun(alias);
	}
}
