/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkDetails extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord> {

	private static final long serialVersionUID = 434823898;

	/**
	 * The singleton instance of <code>cloud.network_details</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NetworkDetails NETWORK_DETAILS = new org.apache.cloudstack.db.jooq.tables.NetworkDetails();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord.class;
	}

	/**
	 * The column <code>cloud.network_details.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.network_details.network_id</code>. network id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord, java.lang.Long> NETWORK_ID = createField("network_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.network_details.name</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.network_details.value</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this);

	/**
	 * The column <code>cloud.network_details.display_detail</code>. Should detail be displayed to the end user
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord, java.lang.Byte> DISPLAY_DETAIL = createField("display_detail", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this);

	/**
	 * Create a <code>cloud.network_details</code> table reference
	 */
	public NetworkDetails() {
		super("network_details", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.network_details</code> table reference
	 */
	public NetworkDetails(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_NETWORK_DETAILS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_NETWORK_DETAILS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_NETWORK_DETAILS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_NETWORK_DETAILS__NETWORK_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.NetworkDetails as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.NetworkDetails(alias);
	}
}
