/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NiciraNvpNicMap extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord> {

	private static final long serialVersionUID = 876916658;

	/**
	 * The singleton instance of <code>cloud.nicira_nvp_nic_map</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NiciraNvpNicMap NICIRA_NVP_NIC_MAP = new org.apache.cloudstack.db.jooq.tables.NiciraNvpNicMap();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord.class;
	}

	/**
	 * The column <code>cloud.nicira_nvp_nic_map.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.nicira_nvp_nic_map.logicalswitch</code>. nicira uuid of logical switch this port is provisioned on
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord, java.lang.String> LOGICALSWITCH = createField("logicalswitch", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.nicira_nvp_nic_map.logicalswitchport</code>. nicira uuid of this logical switch port
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord, java.lang.String> LOGICALSWITCHPORT = createField("logicalswitchport", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cloud.nicira_nvp_nic_map.nic</code>. cloudstack uuid of the nic connected to this logical switch port
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord, java.lang.String> NIC = createField("nic", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>cloud.nicira_nvp_nic_map</code> table reference
	 */
	public NiciraNvpNicMap() {
		super("nicira_nvp_nic_map", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.nicira_nvp_nic_map</code> table reference
	 */
	public NiciraNvpNicMap(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.NiciraNvpNicMap.NICIRA_NVP_NIC_MAP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_NICIRA_NVP_NIC_MAP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_NICIRA_NVP_NIC_MAP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_NICIRA_NVP_NIC_MAP_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_NICIRA_NVP_NIC_MAP_LOGICALSWITCHPORT, org.apache.cloudstack.db.jooq.Keys.KEY_NICIRA_NVP_NIC_MAP_NIC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.NiciraNvpNicMapRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_NICIRA_NVP_NIC_MAP__NIC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.NiciraNvpNicMap as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.NiciraNvpNicMap(alias);
	}
}
