/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NtwkServiceMap extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord> {

	private static final long serialVersionUID = -1554236417;

	/**
	 * The singleton instance of <code>cloud.ntwk_service_map</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.NtwkServiceMap NTWK_SERVICE_MAP = new org.apache.cloudstack.db.jooq.tables.NtwkServiceMap();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord.class;
	}

	/**
	 * The column <code>cloud.ntwk_service_map.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.ntwk_service_map.network_id</code>. network_id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord, java.lang.Long> NETWORK_ID = createField("network_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.ntwk_service_map.service</code>. service
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord, java.lang.String> SERVICE = createField("service", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>cloud.ntwk_service_map.provider</code>. service provider
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord, java.lang.String> PROVIDER = createField("provider", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cloud.ntwk_service_map.created</code>. date created
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>cloud.ntwk_service_map</code> table reference
	 */
	public NtwkServiceMap() {
		super("ntwk_service_map", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.ntwk_service_map</code> table reference
	 */
	public NtwkServiceMap(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.NtwkServiceMap.NTWK_SERVICE_MAP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_NTWK_SERVICE_MAP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_NTWK_SERVICE_MAP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_NTWK_SERVICE_MAP_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_NTWK_SERVICE_MAP_NETWORK_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.NtwkServiceMapRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_NTWK_SERVICE_MAP__NETWORK_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.NtwkServiceMap as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.NtwkServiceMap(alias);
	}
}
