/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpDcIpAddressAlloc extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord> {

	private static final long serialVersionUID = 1150003007;

	/**
	 * The singleton instance of <code>cloud.op_dc_ip_address_alloc</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpDcIpAddressAlloc OP_DC_IP_ADDRESS_ALLOC = new org.apache.cloudstack.db.jooq.tables.OpDcIpAddressAlloc();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord.class;
	}

	/**
	 * The column <code>cloud.op_dc_ip_address_alloc.id</code>. primary key
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.op_dc_ip_address_alloc.ip_address</code>. ip address
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, java.lang.String> IP_ADDRESS = createField("ip_address", org.jooq.impl.SQLDataType.CHAR.length(40).nullable(false), this);

	/**
	 * The column <code>cloud.op_dc_ip_address_alloc.data_center_id</code>. data center it belongs to
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, java.lang.Long> DATA_CENTER_ID = createField("data_center_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.op_dc_ip_address_alloc.pod_id</code>. pod it belongs to
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, java.lang.Long> POD_ID = createField("pod_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.op_dc_ip_address_alloc.nic_id</code>. nic id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, java.lang.Long> NIC_ID = createField("nic_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.op_dc_ip_address_alloc.reservation_id</code>. reservation id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, java.lang.String> RESERVATION_ID = createField("reservation_id", org.jooq.impl.SQLDataType.CHAR.length(40), this);

	/**
	 * The column <code>cloud.op_dc_ip_address_alloc.taken</code>. Date taken
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, java.sql.Timestamp> TAKEN = createField("taken", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.op_dc_ip_address_alloc.mac_address</code>. mac address for management ips
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, java.lang.Long> MAC_ADDRESS = createField("mac_address", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * Create a <code>cloud.op_dc_ip_address_alloc</code> table reference
	 */
	public OpDcIpAddressAlloc() {
		super("op_dc_ip_address_alloc", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.op_dc_ip_address_alloc</code> table reference
	 */
	public OpDcIpAddressAlloc(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.OpDcIpAddressAlloc.OP_DC_IP_ADDRESS_ALLOC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_OP_DC_IP_ADDRESS_ALLOC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_OP_DC_IP_ADDRESS_ALLOC_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_OP_DC_IP_ADDRESS_ALLOC_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_OP_DC_IP_ADDRESS_ALLOC_I_OP_DC_IP_ADDRESS_ALLOC__IP_ADDRESS__DATA_CENTER_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.OpDcIpAddressAllocRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_OP_DC_IP_ADDRESS_ALLOC__DATA_CENTER_ID, org.apache.cloudstack.db.jooq.Keys.FK_OP_DC_IP_ADDRESS_ALLOC__POD_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.OpDcIpAddressAlloc as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.OpDcIpAddressAlloc(alias);
	}
}
