/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpDcStorageNetworkIpAddress extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord> {

	private static final long serialVersionUID = 49535319;

	/**
	 * The singleton instance of <code>cloud.op_dc_storage_network_ip_address</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpDcStorageNetworkIpAddress OP_DC_STORAGE_NETWORK_IP_ADDRESS = new org.apache.cloudstack.db.jooq.tables.OpDcStorageNetworkIpAddress();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord.class;
	}

	/**
	 * The column <code>cloud.op_dc_storage_network_ip_address.id</code>. primary key
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.op_dc_storage_network_ip_address.range_id</code>. id of ip range in dc_storage_network_ip_range
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord, java.lang.Long> RANGE_ID = createField("range_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.op_dc_storage_network_ip_address.ip_address</code>. ip address
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord, java.lang.String> IP_ADDRESS = createField("ip_address", org.jooq.impl.SQLDataType.CHAR.length(40).nullable(false), this);

	/**
	 * The column <code>cloud.op_dc_storage_network_ip_address.mac_address</code>. mac address for storage ips
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord, java.lang.Long> MAC_ADDRESS = createField("mac_address", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.op_dc_storage_network_ip_address.taken</code>. Date taken
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord, java.sql.Timestamp> TAKEN = createField("taken", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>cloud.op_dc_storage_network_ip_address</code> table reference
	 */
	public OpDcStorageNetworkIpAddress() {
		super("op_dc_storage_network_ip_address", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.op_dc_storage_network_ip_address</code> table reference
	 */
	public OpDcStorageNetworkIpAddress(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.OpDcStorageNetworkIpAddress.OP_DC_STORAGE_NETWORK_IP_ADDRESS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_OP_DC_STORAGE_NETWORK_IP_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_OP_DC_STORAGE_NETWORK_IP_ADDRESS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_OP_DC_STORAGE_NETWORK_IP_ADDRESS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.OpDcStorageNetworkIpAddressRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_STORAGE_IP_ADDRESS__RANGE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.OpDcStorageNetworkIpAddress as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.OpDcStorageNetworkIpAddress(alias);
	}
}
