/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpPodVlanAlloc extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord> {

	private static final long serialVersionUID = 1778729631;

	/**
	 * The singleton instance of <code>cloud.op_pod_vlan_alloc</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.OpPodVlanAlloc OP_POD_VLAN_ALLOC = new org.apache.cloudstack.db.jooq.tables.OpPodVlanAlloc();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord.class;
	}

	/**
	 * The column <code>cloud.op_pod_vlan_alloc.id</code>. primary id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.op_pod_vlan_alloc.vlan</code>. vlan id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord, java.lang.String> VLAN = createField("vlan", org.jooq.impl.SQLDataType.VARCHAR.length(18).nullable(false), this);

	/**
	 * The column <code>cloud.op_pod_vlan_alloc.data_center_id</code>. data center the pod belongs to
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord, java.lang.Long> DATA_CENTER_ID = createField("data_center_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.op_pod_vlan_alloc.pod_id</code>. pod the vlan belongs to
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord, java.lang.Long> POD_ID = createField("pod_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.op_pod_vlan_alloc.account_id</code>. account the vlan belongs to right now
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.op_pod_vlan_alloc.taken</code>. Date taken
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord, java.sql.Timestamp> TAKEN = createField("taken", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>cloud.op_pod_vlan_alloc</code> table reference
	 */
	public OpPodVlanAlloc() {
		super("op_pod_vlan_alloc", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.op_pod_vlan_alloc</code> table reference
	 */
	public OpPodVlanAlloc(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.OpPodVlanAlloc.OP_POD_VLAN_ALLOC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_OP_POD_VLAN_ALLOC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_OP_POD_VLAN_ALLOC_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.OpPodVlanAllocRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_OP_POD_VLAN_ALLOC_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.OpPodVlanAlloc as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.OpPodVlanAlloc(alias);
	}
}
