/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceOffering extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord> {

	private static final long serialVersionUID = 1323344809;

	/**
	 * The singleton instance of <code>cloud.service_offering</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.ServiceOffering SERVICE_OFFERING = new org.apache.cloudstack.db.jooq.tables.ServiceOffering();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord.class;
	}

	/**
	 * The column <code>cloud.service_offering.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.service_offering.cpu</code>. # of cores
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Integer> CPU = createField("cpu", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>cloud.service_offering.speed</code>. speed per core in mhz
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Integer> SPEED = createField("speed", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>cloud.service_offering.ram_size</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Long> RAM_SIZE = createField("ram_size", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.service_offering.nw_rate</code>. network rate throttle mbits/s
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Short> NW_RATE = createField("nw_rate", org.jooq.impl.SQLDataType.SMALLINT.defaulted(true), this);

	/**
	 * The column <code>cloud.service_offering.mc_rate</code>. mcast rate throttle mbits/s
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Short> MC_RATE = createField("mc_rate", org.jooq.impl.SQLDataType.SMALLINT.defaulted(true), this);

	/**
	 * The column <code>cloud.service_offering.ha_enabled</code>. Enable HA
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Byte> HA_ENABLED = createField("ha_enabled", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this);

	/**
	 * The column <code>cloud.service_offering.limit_cpu_use</code>. Limit the CPU usage to service offering
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Byte> LIMIT_CPU_USE = createField("limit_cpu_use", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this);

	/**
	 * The column <code>cloud.service_offering.host_tag</code>. host tag specified by the service_offering
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.String> HOST_TAG = createField("host_tag", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cloud.service_offering.default_use</code>. is this offering a default system offering
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Byte> DEFAULT_USE = createField("default_use", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this);

	/**
	 * The column <code>cloud.service_offering.vm_type</code>. type of offering specified for system offerings
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.String> VM_TYPE = createField("vm_type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this);

	/**
	 * The column <code>cloud.service_offering.sort_key</code>. sort key used for customising sort method
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Integer> SORT_KEY = createField("sort_key", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>cloud.service_offering.is_volatile</code>. true if the vm needs to be volatile, i.e., on every reboot of vm from API root disk is discarded and creates a new root disk
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.Byte> IS_VOLATILE = createField("is_volatile", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this);

	/**
	 * The column <code>cloud.service_offering.deployment_planner</code>. Planner heuristics used to deploy a VM of this offering; if null global config vm.deployment.planner is used
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, java.lang.String> DEPLOYMENT_PLANNER = createField("deployment_planner", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>cloud.service_offering</code> table reference
	 */
	public ServiceOffering() {
		super("service_offering", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.service_offering</code> table reference
	 */
	public ServiceOffering(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.ServiceOffering.SERVICE_OFFERING);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_SERVICE_OFFERING_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_SERVICE_OFFERING_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.ServiceOfferingRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_SERVICE_OFFERING__ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.ServiceOffering as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.ServiceOffering(alias);
	}
}
