/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SnapshotSchedule extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord> {

	private static final long serialVersionUID = 487498580;

	/**
	 * The singleton instance of <code>cloud.snapshot_schedule</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SnapshotSchedule SNAPSHOT_SCHEDULE = new org.apache.cloudstack.db.jooq.tables.SnapshotSchedule();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord.class;
	}

	/**
	 * The column <code>cloud.snapshot_schedule.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.snapshot_schedule.uuid</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>cloud.snapshot_schedule.volume_id</code>. The volume for which this snapshot is being taken
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, java.lang.Long> VOLUME_ID = createField("volume_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.snapshot_schedule.policy_id</code>. One of the policyIds for which this snapshot was taken
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, java.lang.Long> POLICY_ID = createField("policy_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.snapshot_schedule.scheduled_timestamp</code>. Time at which the snapshot was scheduled for execution
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, java.sql.Timestamp> SCHEDULED_TIMESTAMP = createField("scheduled_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>cloud.snapshot_schedule.async_job_id</code>. If this schedule is being executed, it is the id of the create aysnc_job. Before that it is null
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, java.lang.Long> ASYNC_JOB_ID = createField("async_job_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.snapshot_schedule.snapshot_id</code>. If this schedule is being executed, then the corresponding snapshot has this id. Before that it is null
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, java.lang.Long> SNAPSHOT_ID = createField("snapshot_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>cloud.snapshot_schedule</code> table reference
	 */
	public SnapshotSchedule() {
		super("snapshot_schedule", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.snapshot_schedule</code> table reference
	 */
	public SnapshotSchedule(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.SnapshotSchedule.SNAPSHOT_SCHEDULE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_SNAPSHOT_SCHEDULE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_SNAPSHOT_SCHEDULE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_SNAPSHOT_SCHEDULE_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_SNAPSHOT_SCHEDULE_UC_SNAPSHOT_SCHEDULE__UUID, org.apache.cloudstack.db.jooq.Keys.KEY_SNAPSHOT_SCHEDULE_VOLUME_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.SnapshotScheduleRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK__SNAPSHOT_SCHEDULE_VOLUME_ID, org.apache.cloudstack.db.jooq.Keys.FK__SNAPSHOT_SCHEDULE_POLICY_ID, org.apache.cloudstack.db.jooq.Keys.FK__SNAPSHOT_SCHEDULE_ASYNC_JOB_ID, org.apache.cloudstack.db.jooq.Keys.FK__SNAPSHOT_SCHEDULE_SNAPSHOT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.SnapshotSchedule as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.SnapshotSchedule(alias);
	}
}
