/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SshKeypairs extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord> {

	private static final long serialVersionUID = 310824400;

	/**
	 * The singleton instance of <code>cloud.ssh_keypairs</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SshKeypairs SSH_KEYPAIRS = new org.apache.cloudstack.db.jooq.tables.SshKeypairs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord.class;
	}

	/**
	 * The column <code>cloud.ssh_keypairs.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.ssh_keypairs.account_id</code>. owner, foreign key to account table
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.ssh_keypairs.domain_id</code>. domain, foreign key to domain table
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord, java.lang.Long> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.ssh_keypairs.keypair_name</code>. name of the key pair
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord, java.lang.String> KEYPAIR_NAME = createField("keypair_name", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this);

	/**
	 * The column <code>cloud.ssh_keypairs.fingerprint</code>. fingerprint for the ssh public key
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord, java.lang.String> FINGERPRINT = createField("fingerprint", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this);

	/**
	 * The column <code>cloud.ssh_keypairs.public_key</code>. public key of the ssh key pair
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord, java.lang.String> PUBLIC_KEY = createField("public_key", org.jooq.impl.SQLDataType.VARCHAR.length(5120).nullable(false), this);

	/**
	 * Create a <code>cloud.ssh_keypairs</code> table reference
	 */
	public SshKeypairs() {
		super("ssh_keypairs", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.ssh_keypairs</code> table reference
	 */
	public SshKeypairs(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.SshKeypairs.SSH_KEYPAIRS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_SSH_KEYPAIRS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_SSH_KEYPAIRS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_SSH_KEYPAIRS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.SshKeypairsRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_SSH_KEYPAIRS__ACCOUNT_ID, org.apache.cloudstack.db.jooq.Keys.FK_SSH_KEYPAIRS__DOMAIN_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.SshKeypairs as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.SshKeypairs(alias);
	}
}
