/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SyncQueue extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord> {

	private static final long serialVersionUID = -1219692740;

	/**
	 * The singleton instance of <code>cloud.sync_queue</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SyncQueue SYNC_QUEUE = new org.apache.cloudstack.db.jooq.tables.SyncQueue();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord.class;
	}

	/**
	 * The column <code>cloud.sync_queue.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.sync_queue.sync_objtype</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord, java.lang.String> SYNC_OBJTYPE = createField("sync_objtype", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this);

	/**
	 * The column <code>cloud.sync_queue.sync_objid</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord, java.lang.Long> SYNC_OBJID = createField("sync_objid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.sync_queue.queue_proc_number</code>. process number, increase 1 for each iteration
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord, java.lang.Long> QUEUE_PROC_NUMBER = createField("queue_proc_number", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.sync_queue.created</code>. date created
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.sync_queue.last_updated</code>. date created
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord, java.sql.Timestamp> LAST_UPDATED = createField("last_updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.sync_queue.queue_size</code>. number of items being processed by the queue
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord, java.lang.Short> QUEUE_SIZE = createField("queue_size", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this);

	/**
	 * The column <code>cloud.sync_queue.queue_size_limit</code>. max number of items the queue can process concurrently
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord, java.lang.Short> QUEUE_SIZE_LIMIT = createField("queue_size_limit", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this);

	/**
	 * Create a <code>cloud.sync_queue</code> table reference
	 */
	public SyncQueue() {
		super("sync_queue", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.sync_queue</code> table reference
	 */
	public SyncQueue(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.SyncQueue.SYNC_QUEUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_SYNC_QUEUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_SYNC_QUEUE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.SyncQueueRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_SYNC_QUEUE_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_SYNC_QUEUE_I_SYNC_QUEUE__OBJTYPE__OBJID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.SyncQueue as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.SyncQueue(alias);
	}
}
