/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemVm extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.SystemVmRecord> {

	private static final long serialVersionUID = 1311585448;

	/**
	 * The singleton instance of <code>cloud.system_vm</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.SystemVm SYSTEM_VM = new org.apache.cloudstack.db.jooq.tables.SystemVm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.SystemVmRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.SystemVmRecord.class;
	}

	/**
	 * The column <code>cloud.system_vm.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SystemVmRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.system_vm.role</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.SystemVmRecord, java.lang.String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this);

	/**
	 * Create a <code>cloud.system_vm</code> table reference
	 */
	public SystemVm() {
		super("system_vm", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.system_vm</code> table reference
	 */
	public SystemVm(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.SystemVm.SYSTEM_VM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.SystemVm as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.SystemVm(alias);
	}
}
