/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserVm extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord> {

	private static final long serialVersionUID = -556733232;

	/**
	 * The singleton instance of <code>cloud.user_vm</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.UserVm USER_VM = new org.apache.cloudstack.db.jooq.tables.UserVm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.UserVmRecord.class;
	}

	/**
	 * The column <code>cloud.user_vm.id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.user_vm.iso_id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord, java.lang.Long> ISO_ID = createField("iso_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>cloud.user_vm.display_name</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord, java.lang.String> DISPLAY_NAME = createField("display_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cloud.user_vm.user_data</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord, java.lang.String> USER_DATA = createField("user_data", org.jooq.impl.SQLDataType.CLOB.length(16777215), this);

	/**
	 * The column <code>cloud.user_vm.update_parameters</code>. Defines if the parameters have been updated for the vm
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord, java.lang.Byte> UPDATE_PARAMETERS = createField("update_parameters", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this);

	/**
	 * Create a <code>cloud.user_vm</code> table reference
	 */
	public UserVm() {
		super("user_vm", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.user_vm</code> table reference
	 */
	public UserVm(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.UserVm.USER_VM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_USER_VM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_USER_VM_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_USER_VM_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_USER_VM__ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.UserVm as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.UserVm(alias);
	}
}
