/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VmReservation extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord> {

	private static final long serialVersionUID = -536750945;

	/**
	 * The singleton instance of <code>cloud.vm_reservation</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmReservation VM_RESERVATION = new org.apache.cloudstack.db.jooq.tables.VmReservation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord.class;
	}

	/**
	 * The column <code>cloud.vm_reservation.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vm_reservation.uuid</code>. reservation id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this);

	/**
	 * The column <code>cloud.vm_reservation.vm_id</code>. vm id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.lang.Long> VM_ID = createField("vm_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vm_reservation.data_center_id</code>. zone id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.lang.Long> DATA_CENTER_ID = createField("data_center_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vm_reservation.pod_id</code>. pod id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.lang.Long> POD_ID = createField("pod_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vm_reservation.cluster_id</code>. cluster id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.lang.Long> CLUSTER_ID = createField("cluster_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vm_reservation.host_id</code>. host id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.lang.Long> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vm_reservation.created</code>. date created
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.vm_reservation.removed</code>. date removed if not null
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.sql.Timestamp> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>cloud.vm_reservation</code> table reference
	 */
	public VmReservation() {
		super("vm_reservation", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.vm_reservation</code> table reference
	 */
	public VmReservation(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.VmReservation.VM_RESERVATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_VM_RESERVATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_VM_RESERVATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.VmReservationRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_VM_RESERVATION_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_VM_RESERVATION_UC_VM_RESERVATION__UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.VmReservation as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.VmReservation(alias);
	}
}
