/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VmRootDiskTags extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord> {

	private static final long serialVersionUID = 1997478618;

	/**
	 * The singleton instance of <code>cloud.vm_root_disk_tags</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VmRootDiskTags VM_ROOT_DISK_TAGS = new org.apache.cloudstack.db.jooq.tables.VmRootDiskTags();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord.class;
	}

	/**
	 * The column <code>cloud.vm_root_disk_tags.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vm_root_disk_tags.vm_id</code>. vm id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord, java.lang.Long> VM_ID = createField("vm_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vm_root_disk_tags.root_disk_tag</code>. name of tag
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord, java.lang.String> ROOT_DISK_TAG = createField("root_disk_tag", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * Create a <code>cloud.vm_root_disk_tags</code> table reference
	 */
	public VmRootDiskTags() {
		super("vm_root_disk_tags", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.vm_root_disk_tags</code> table reference
	 */
	public VmRootDiskTags(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.VmRootDiskTags.VM_ROOT_DISK_TAGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_VM_ROOT_DISK_TAGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_VM_ROOT_DISK_TAGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.VmRootDiskTagsRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_VM_ROOT_DISK_TAGS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.VmRootDiskTags as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.VmRootDiskTags(alias);
	}
}
