/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VpcGateways extends org.jooq.impl.TableImpl<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord> {

	private static final long serialVersionUID = -1157500270;

	/**
	 * The singleton instance of <code>cloud.vpc_gateways</code>
	 */
	public static final org.apache.cloudstack.db.jooq.tables.VpcGateways VPC_GATEWAYS = new org.apache.cloudstack.db.jooq.tables.VpcGateways();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord> getRecordType() {
		return org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord.class;
	}

	/**
	 * The column <code>cloud.vpc_gateways.id</code>. id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vpc_gateways.uuid</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>cloud.vpc_gateways.ip4_address</code>. ip4 address of the gateway
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.String> IP4_ADDRESS = createField("ip4_address", org.jooq.impl.SQLDataType.CHAR.length(40), this);

	/**
	 * The column <code>cloud.vpc_gateways.netmask</code>. netmask of the gateway
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.String> NETMASK = createField("netmask", org.jooq.impl.SQLDataType.VARCHAR.length(15), this);

	/**
	 * The column <code>cloud.vpc_gateways.gateway</code>. gateway
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.String> GATEWAY = createField("gateway", org.jooq.impl.SQLDataType.VARCHAR.length(15), this);

	/**
	 * The column <code>cloud.vpc_gateways.vlan_tag</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.String> VLAN_TAG = createField("vlan_tag", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>cloud.vpc_gateways.type</code>. type of gateway; can be Public/Private/Vpn
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this);

	/**
	 * The column <code>cloud.vpc_gateways.network_id</code>. network id vpc gateway belongs to
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.Long> NETWORK_ID = createField("network_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vpc_gateways.vpc_id</code>. id of the vpc the gateway belongs to
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.Long> VPC_ID = createField("vpc_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vpc_gateways.zone_id</code>. id of the zone the gateway belongs to
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.Long> ZONE_ID = createField("zone_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vpc_gateways.created</code>. date created
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.vpc_gateways.account_id</code>. owner id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vpc_gateways.domain_id</code>. domain id
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.Long> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>cloud.vpc_gateways.state</code>. what state the vpc gateway in
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this);

	/**
	 * The column <code>cloud.vpc_gateways.removed</code>. date removed if not null
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.sql.Timestamp> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>cloud.vpc_gateways.source_nat</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.Byte> SOURCE_NAT = createField("source_nat", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this);

	/**
	 * The column <code>cloud.vpc_gateways.network_acl_id</code>. 
	 */
	public final org.jooq.TableField<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.Long> NETWORK_ACL_ID = createField("network_acl_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this);

	/**
	 * Create a <code>cloud.vpc_gateways</code> table reference
	 */
	public VpcGateways() {
		super("vpc_gateways", org.apache.cloudstack.db.jooq.Cloud.CLOUD);
	}

	/**
	 * Create an aliased <code>cloud.vpc_gateways</code> table reference
	 */
	public VpcGateways(java.lang.String alias) {
		super(alias, org.apache.cloudstack.db.jooq.Cloud.CLOUD, org.apache.cloudstack.db.jooq.tables.VpcGateways.VPC_GATEWAYS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, java.lang.Long> getIdentity() {
		return org.apache.cloudstack.db.jooq.Keys.IDENTITY_VPC_GATEWAYS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord> getPrimaryKey() {
		return org.apache.cloudstack.db.jooq.Keys.KEY_VPC_GATEWAYS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord>>asList(org.apache.cloudstack.db.jooq.Keys.KEY_VPC_GATEWAYS_PRIMARY, org.apache.cloudstack.db.jooq.Keys.KEY_VPC_GATEWAYS_ID, org.apache.cloudstack.db.jooq.Keys.KEY_VPC_GATEWAYS_UC_VPC_GATEWAYS__UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.apache.cloudstack.db.jooq.tables.records.VpcGatewaysRecord, ?>>asList(org.apache.cloudstack.db.jooq.Keys.FK_VPC_GATEWAYS__NETWORK_ID, org.apache.cloudstack.db.jooq.Keys.FK_VPC_GATEWAYS__VPC_ID, org.apache.cloudstack.db.jooq.Keys.FK_VPC_GATEWAYS__ZONE_ID, org.apache.cloudstack.db.jooq.Keys.FK_VPC_GATEWAYS__ACCOUNT_ID, org.apache.cloudstack.db.jooq.Keys.FK_VPC_GATEWAYS__DOMAIN_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.apache.cloudstack.db.jooq.tables.VpcGateways as(java.lang.String alias) {
		return new org.apache.cloudstack.db.jooq.tables.VpcGateways(alias);
	}
}
