/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataCenterDetailsDao extends org.jooq.impl.DAOImpl<org.apache.cloudstack.db.jooq.tables.records.DataCenterDetailsRecord, org.apache.cloudstack.db.jooq.tables.pojos.DataCenterDetails, java.lang.Long> {

	/**
	 * Create a new DataCenterDetailsDao without any configuration
	 */
	public DataCenterDetailsDao() {
		super(org.apache.cloudstack.db.jooq.tables.DataCenterDetails.DATA_CENTER_DETAILS, org.apache.cloudstack.db.jooq.tables.pojos.DataCenterDetails.class);
	}

	/**
	 * Create a new DataCenterDetailsDao with an attached configuration
	 */
	public DataCenterDetailsDao(org.jooq.Configuration configuration) {
		super(org.apache.cloudstack.db.jooq.tables.DataCenterDetails.DATA_CENTER_DETAILS, org.apache.cloudstack.db.jooq.tables.pojos.DataCenterDetails.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(org.apache.cloudstack.db.jooq.tables.pojos.DataCenterDetails object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.DataCenterDetails> fetchById(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.DataCenterDetails.DATA_CENTER_DETAILS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.apache.cloudstack.db.jooq.tables.pojos.DataCenterDetails fetchOneById(java.lang.Long value) {
		return fetchOne(org.apache.cloudstack.db.jooq.tables.DataCenterDetails.DATA_CENTER_DETAILS.ID, value);
	}

	/**
	 * Fetch records that have <code>dc_id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.DataCenterDetails> fetchByDcId(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.DataCenterDetails.DATA_CENTER_DETAILS.DC_ID, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.DataCenterDetails> fetchByName(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.DataCenterDetails.DATA_CENTER_DETAILS.NAME, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.DataCenterDetails> fetchByValue(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.DataCenterDetails.DATA_CENTER_DETAILS.VALUE, values);
	}
}
