/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventDao extends org.jooq.impl.DAOImpl<org.apache.cloudstack.db.jooq.tables.records.EventRecord, org.apache.cloudstack.db.jooq.tables.pojos.Event, java.lang.Long> {

	/**
	 * Create a new EventDao without any configuration
	 */
	public EventDao() {
		super(org.apache.cloudstack.db.jooq.tables.Event.EVENT, org.apache.cloudstack.db.jooq.tables.pojos.Event.class);
	}

	/**
	 * Create a new EventDao with an attached configuration
	 */
	public EventDao(org.jooq.Configuration configuration) {
		super(org.apache.cloudstack.db.jooq.tables.Event.EVENT, org.apache.cloudstack.db.jooq.tables.pojos.Event.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(org.apache.cloudstack.db.jooq.tables.pojos.Event object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchById(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.apache.cloudstack.db.jooq.tables.pojos.Event fetchOneById(java.lang.Long value) {
		return fetchOne(org.apache.cloudstack.db.jooq.tables.Event.EVENT.ID, value);
	}

	/**
	 * Fetch records that have <code>uuid IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByUuid(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.UUID, values);
	}

	/**
	 * Fetch a unique record that has <code>uuid = value</code>
	 */
	public org.apache.cloudstack.db.jooq.tables.pojos.Event fetchOneByUuid(java.lang.String value) {
		return fetchOne(org.apache.cloudstack.db.jooq.tables.Event.EVENT.UUID, value);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByType(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.TYPE, values);
	}

	/**
	 * Fetch records that have <code>state IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByState(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.STATE, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByDescription(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByUserId(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>account_id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByAccountId(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.ACCOUNT_ID, values);
	}

	/**
	 * Fetch records that have <code>domain_id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByDomainId(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.DOMAIN_ID, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.CREATED, values);
	}

	/**
	 * Fetch records that have <code>level IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByLevel(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.LEVEL, values);
	}

	/**
	 * Fetch records that have <code>start_id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByStartId(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.START_ID, values);
	}

	/**
	 * Fetch records that have <code>parameters IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByParameters(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.PARAMETERS, values);
	}

	/**
	 * Fetch records that have <code>archived IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.Event> fetchByArchived(java.lang.Byte... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.Event.EVENT.ARCHIVED, values);
	}
}
