/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkDetailsDao extends org.jooq.impl.DAOImpl<org.apache.cloudstack.db.jooq.tables.records.NetworkDetailsRecord, org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails, java.lang.Long> {

	/**
	 * Create a new NetworkDetailsDao without any configuration
	 */
	public NetworkDetailsDao() {
		super(org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS, org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails.class);
	}

	/**
	 * Create a new NetworkDetailsDao with an attached configuration
	 */
	public NetworkDetailsDao(org.jooq.Configuration configuration) {
		super(org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS, org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails> fetchById(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails fetchOneById(java.lang.Long value) {
		return fetchOne(org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS.ID, value);
	}

	/**
	 * Fetch records that have <code>network_id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails> fetchByNetworkId(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS.NETWORK_ID, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails> fetchByName(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS.NAME, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails> fetchByValue(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS.VALUE, values);
	}

	/**
	 * Fetch records that have <code>display_detail IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.NetworkDetails> fetchByDisplayDetail(java.lang.Byte... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.NetworkDetails.NETWORK_DETAILS.DISPLAY_DETAIL, values);
	}
}
