/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateStoreRefDao extends org.jooq.impl.DAOImpl<org.apache.cloudstack.db.jooq.tables.records.TemplateStoreRefRecord, org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef, java.lang.Long> {

	/**
	 * Create a new TemplateStoreRefDao without any configuration
	 */
	public TemplateStoreRefDao() {
		super(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF, org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef.class);
	}

	/**
	 * Create a new TemplateStoreRefDao with an attached configuration
	 */
	public TemplateStoreRefDao(org.jooq.Configuration configuration) {
		super(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF, org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchById(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef fetchOneById(java.lang.Long value) {
		return fetchOne(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.ID, value);
	}

	/**
	 * Fetch records that have <code>store_id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByStoreId(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.STORE_ID, values);
	}

	/**
	 * Fetch records that have <code>template_id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByTemplateId(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.TEMPLATE_ID, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.CREATED, values);
	}

	/**
	 * Fetch records that have <code>last_updated IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByLastUpdated(java.sql.Timestamp... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.LAST_UPDATED, values);
	}

	/**
	 * Fetch records that have <code>job_id IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByJobId(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.JOB_ID, values);
	}

	/**
	 * Fetch records that have <code>download_pct IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByDownloadPct(java.lang.Integer... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.DOWNLOAD_PCT, values);
	}

	/**
	 * Fetch records that have <code>size IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchBySize(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.SIZE, values);
	}

	/**
	 * Fetch records that have <code>store_role IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByStoreRole(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.STORE_ROLE, values);
	}

	/**
	 * Fetch records that have <code>physical_size IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByPhysicalSize(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.PHYSICAL_SIZE, values);
	}

	/**
	 * Fetch records that have <code>download_state IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByDownloadState(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.DOWNLOAD_STATE, values);
	}

	/**
	 * Fetch records that have <code>error_str IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByErrorStr(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.ERROR_STR, values);
	}

	/**
	 * Fetch records that have <code>local_path IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByLocalPath(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.LOCAL_PATH, values);
	}

	/**
	 * Fetch records that have <code>install_path IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByInstallPath(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.INSTALL_PATH, values);
	}

	/**
	 * Fetch records that have <code>url IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByUrl(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.URL, values);
	}

	/**
	 * Fetch records that have <code>state IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByState(java.lang.String... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.STATE, values);
	}

	/**
	 * Fetch records that have <code>destroyed IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByDestroyed(java.lang.Byte... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.DESTROYED, values);
	}

	/**
	 * Fetch records that have <code>is_copy IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByIsCopy(java.lang.Byte... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.IS_COPY, values);
	}

	/**
	 * Fetch records that have <code>update_count IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByUpdateCount(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.UPDATE_COUNT, values);
	}

	/**
	 * Fetch records that have <code>ref_cnt IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByRefCnt(java.lang.Long... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.REF_CNT, values);
	}

	/**
	 * Fetch records that have <code>updated IN (values)</code>
	 */
	public java.util.List<org.apache.cloudstack.db.jooq.tables.pojos.TemplateStoreRef> fetchByUpdated(java.sql.Timestamp... values) {
		return fetch(org.apache.cloudstack.db.jooq.tables.TemplateStoreRef.TEMPLATE_STORE_REF.UPDATED, values);
	}
}
