/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "disk_offering_view", schema = "cloud")
public class DiskOfferingViewRecord extends org.jooq.impl.TableRecordImpl<org.apache.cloudstack.db.jooq.tables.records.DiskOfferingViewRecord> {

	private static final long serialVersionUID = 523338418;

	/**
	 * Setter for <code>cloud.disk_offering_view.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.id</code>. 
	 */
	@javax.persistence.Column(name = "id", nullable = false, precision = 20)
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.uuid</code>. 
	 */
	public void setUuid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.uuid</code>. 
	 */
	@javax.persistence.Column(name = "uuid", length = 40)
	public java.lang.String getUuid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.name</code>. 
	 */
	@javax.persistence.Column(name = "name", nullable = false, length = 255)
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.display_text</code>. Descrianaption text set by the admin for display purpose only
	 */
	public void setDisplayText(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.display_text</code>. Descrianaption text set by the admin for display purpose only
	 */
	@javax.persistence.Column(name = "display_text", length = 4096)
	public java.lang.String getDisplayText() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.disk_size</code>. disk space in byte
	 */
	public void setDiskSize(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.disk_size</code>. disk space in byte
	 */
	@javax.persistence.Column(name = "disk_size", nullable = false, precision = 20)
	public java.lang.Long getDiskSize() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.min_iops</code>. Minimum IOPS
	 */
	public void setMinIops(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.min_iops</code>. Minimum IOPS
	 */
	@javax.persistence.Column(name = "min_iops", precision = 20)
	public java.lang.Long getMinIops() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.max_iops</code>. Maximum IOPS
	 */
	public void setMaxIops(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.max_iops</code>. Maximum IOPS
	 */
	@javax.persistence.Column(name = "max_iops", precision = 20)
	public java.lang.Long getMaxIops() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.created</code>. date the disk offering was created
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.created</code>. date the disk offering was created
	 */
	@javax.persistence.Column(name = "created")
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.tags</code>. comma separated tags about the disk_offering
	 */
	public void setTags(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.tags</code>. comma separated tags about the disk_offering
	 */
	@javax.persistence.Column(name = "tags", length = 4096)
	public java.lang.String getTags() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.customized</code>. 0 implies not customized by default
	 */
	public void setCustomized(java.lang.Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.customized</code>. 0 implies not customized by default
	 */
	@javax.persistence.Column(name = "customized", nullable = false, precision = 3)
	public java.lang.Byte getCustomized() {
		return (java.lang.Byte) getValue(9);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.customized_iops</code>. Should customized IOPS be displayed to the end user
	 */
	public void setCustomizedIops(java.lang.Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.customized_iops</code>. Should customized IOPS be displayed to the end user
	 */
	@javax.persistence.Column(name = "customized_iops", precision = 3)
	public java.lang.Byte getCustomizedIops() {
		return (java.lang.Byte) getValue(10);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.removed</code>. date removed
	 */
	public void setRemoved(java.sql.Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.removed</code>. date removed
	 */
	@javax.persistence.Column(name = "removed")
	public java.sql.Timestamp getRemoved() {
		return (java.sql.Timestamp) getValue(11);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.use_local_storage</code>. Indicates whether local storage pools should be used
	 */
	public void setUseLocalStorage(java.lang.Byte value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.use_local_storage</code>. Indicates whether local storage pools should be used
	 */
	@javax.persistence.Column(name = "use_local_storage", nullable = false, precision = 3)
	public java.lang.Byte getUseLocalStorage() {
		return (java.lang.Byte) getValue(12);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.system_use</code>. is this offering for system used only
	 */
	public void setSystemUse(java.lang.Byte value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.system_use</code>. is this offering for system used only
	 */
	@javax.persistence.Column(name = "system_use", nullable = false, precision = 3)
	public java.lang.Byte getSystemUse() {
		return (java.lang.Byte) getValue(13);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.bytes_read_rate</code>. 
	 */
	public void setBytesReadRate(java.lang.Long value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.bytes_read_rate</code>. 
	 */
	@javax.persistence.Column(name = "bytes_read_rate", precision = 19)
	public java.lang.Long getBytesReadRate() {
		return (java.lang.Long) getValue(14);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.bytes_write_rate</code>. 
	 */
	public void setBytesWriteRate(java.lang.Long value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.bytes_write_rate</code>. 
	 */
	@javax.persistence.Column(name = "bytes_write_rate", precision = 19)
	public java.lang.Long getBytesWriteRate() {
		return (java.lang.Long) getValue(15);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.iops_read_rate</code>. 
	 */
	public void setIopsReadRate(java.lang.Long value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.iops_read_rate</code>. 
	 */
	@javax.persistence.Column(name = "iops_read_rate", precision = 19)
	public java.lang.Long getIopsReadRate() {
		return (java.lang.Long) getValue(16);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.iops_write_rate</code>. 
	 */
	public void setIopsWriteRate(java.lang.Long value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.iops_write_rate</code>. 
	 */
	@javax.persistence.Column(name = "iops_write_rate", precision = 19)
	public java.lang.Long getIopsWriteRate() {
		return (java.lang.Long) getValue(17);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.sort_key</code>. sort key used for customising sort method
	 */
	public void setSortKey(java.lang.Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.sort_key</code>. sort key used for customising sort method
	 */
	@javax.persistence.Column(name = "sort_key", nullable = false, precision = 10)
	public java.lang.Integer getSortKey() {
		return (java.lang.Integer) getValue(18);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.type</code>. inheritted by who?
	 */
	public void setType(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.type</code>. inheritted by who?
	 */
	@javax.persistence.Column(name = "type", length = 32)
	public java.lang.String getType() {
		return (java.lang.String) getValue(19);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.display_offering</code>. Should disk offering be displayed to the end user
	 */
	public void setDisplayOffering(java.lang.Byte value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.display_offering</code>. Should disk offering be displayed to the end user
	 */
	@javax.persistence.Column(name = "display_offering", nullable = false, precision = 3)
	public java.lang.Byte getDisplayOffering() {
		return (java.lang.Byte) getValue(20);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.domain_id</code>. 
	 */
	public void setDomainId(java.lang.Long value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.domain_id</code>. 
	 */
	@javax.persistence.Column(name = "domain_id", precision = 20)
	public java.lang.Long getDomainId() {
		return (java.lang.Long) getValue(21);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.domain_uuid</code>. 
	 */
	public void setDomainUuid(java.lang.String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.domain_uuid</code>. 
	 */
	@javax.persistence.Column(name = "domain_uuid", length = 40)
	public java.lang.String getDomainUuid() {
		return (java.lang.String) getValue(22);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.domain_name</code>. 
	 */
	public void setDomainName(java.lang.String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.domain_name</code>. 
	 */
	@javax.persistence.Column(name = "domain_name", length = 255)
	public java.lang.String getDomainName() {
		return (java.lang.String) getValue(23);
	}

	/**
	 * Setter for <code>cloud.disk_offering_view.domain_path</code>. 
	 */
	public void setDomainPath(java.lang.String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>cloud.disk_offering_view.domain_path</code>. 
	 */
	@javax.persistence.Column(name = "domain_path", length = 255)
	public java.lang.String getDomainPath() {
		return (java.lang.String) getValue(24);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DiskOfferingViewRecord
	 */
	public DiskOfferingViewRecord() {
		super(org.apache.cloudstack.db.jooq.tables.DiskOfferingView.DISK_OFFERING_VIEW);
	}

	/**
	 * Create a detached, initialised DiskOfferingViewRecord
	 */
	public DiskOfferingViewRecord(java.lang.Long id, java.lang.String uuid, java.lang.String name, java.lang.String displayText, java.lang.Long diskSize, java.lang.Long minIops, java.lang.Long maxIops, java.sql.Timestamp created, java.lang.String tags, java.lang.Byte customized, java.lang.Byte customizedIops, java.sql.Timestamp removed, java.lang.Byte useLocalStorage, java.lang.Byte systemUse, java.lang.Long bytesReadRate, java.lang.Long bytesWriteRate, java.lang.Long iopsReadRate, java.lang.Long iopsWriteRate, java.lang.Integer sortKey, java.lang.String type, java.lang.Byte displayOffering, java.lang.Long domainId, java.lang.String domainUuid, java.lang.String domainName, java.lang.String domainPath) {
		super(org.apache.cloudstack.db.jooq.tables.DiskOfferingView.DISK_OFFERING_VIEW);

		setValue(0, id);
		setValue(1, uuid);
		setValue(2, name);
		setValue(3, displayText);
		setValue(4, diskSize);
		setValue(5, minIops);
		setValue(6, maxIops);
		setValue(7, created);
		setValue(8, tags);
		setValue(9, customized);
		setValue(10, customizedIops);
		setValue(11, removed);
		setValue(12, useLocalStorage);
		setValue(13, systemUse);
		setValue(14, bytesReadRate);
		setValue(15, bytesWriteRate);
		setValue(16, iopsReadRate);
		setValue(17, iopsWriteRate);
		setValue(18, sortKey);
		setValue(19, type);
		setValue(20, displayOffering);
		setValue(21, domainId);
		setValue(22, domainUuid);
		setValue(23, domainName);
		setValue(24, domainPath);
	}
}
