/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "host", schema = "cloud")
public class HostRecord extends org.jooq.impl.UpdatableRecordImpl<org.apache.cloudstack.db.jooq.tables.records.HostRecord> {

	private static final long serialVersionUID = -876346125;

	/**
	 * Setter for <code>cloud.host.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cloud.host.id</code>. 
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 20)
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cloud.host.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cloud.host.name</code>. 
	 */
	@javax.persistence.Column(name = "name", nullable = false, length = 255)
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>cloud.host.uuid</code>. this uuid is different with guid below, the later one is used by hypervisor resource
	 */
	public void setUuid(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cloud.host.uuid</code>. this uuid is different with guid below, the later one is used by hypervisor resource
	 */
	@javax.persistence.Column(name = "uuid", unique = true, length = 40)
	public java.lang.String getUuid() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>cloud.host.status</code>. 
	 */
	public void setStatus(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cloud.host.status</code>. 
	 */
	@javax.persistence.Column(name = "status", nullable = false, length = 32)
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>cloud.host.type</code>. 
	 */
	public void setType(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cloud.host.type</code>. 
	 */
	@javax.persistence.Column(name = "type", nullable = false, length = 32)
	public java.lang.String getType() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>cloud.host.private_ip_address</code>. 
	 */
	public void setPrivateIpAddress(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cloud.host.private_ip_address</code>. 
	 */
	@javax.persistence.Column(name = "private_ip_address", nullable = false, length = 40)
	public java.lang.String getPrivateIpAddress() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>cloud.host.private_netmask</code>. 
	 */
	public void setPrivateNetmask(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cloud.host.private_netmask</code>. 
	 */
	@javax.persistence.Column(name = "private_netmask", length = 15)
	public java.lang.String getPrivateNetmask() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>cloud.host.private_mac_address</code>. 
	 */
	public void setPrivateMacAddress(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cloud.host.private_mac_address</code>. 
	 */
	@javax.persistence.Column(name = "private_mac_address", length = 17)
	public java.lang.String getPrivateMacAddress() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>cloud.host.storage_ip_address</code>. 
	 */
	public void setStorageIpAddress(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>cloud.host.storage_ip_address</code>. 
	 */
	@javax.persistence.Column(name = "storage_ip_address", length = 40)
	public java.lang.String getStorageIpAddress() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>cloud.host.storage_netmask</code>. 
	 */
	public void setStorageNetmask(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>cloud.host.storage_netmask</code>. 
	 */
	@javax.persistence.Column(name = "storage_netmask", length = 15)
	public java.lang.String getStorageNetmask() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>cloud.host.storage_mac_address</code>. 
	 */
	public void setStorageMacAddress(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>cloud.host.storage_mac_address</code>. 
	 */
	@javax.persistence.Column(name = "storage_mac_address", length = 17)
	public java.lang.String getStorageMacAddress() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>cloud.host.storage_ip_address_2</code>. 
	 */
	public void setStorageIpAddress_2(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>cloud.host.storage_ip_address_2</code>. 
	 */
	@javax.persistence.Column(name = "storage_ip_address_2", length = 40)
	public java.lang.String getStorageIpAddress_2() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>cloud.host.storage_mac_address_2</code>. 
	 */
	public void setStorageMacAddress_2(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>cloud.host.storage_mac_address_2</code>. 
	 */
	@javax.persistence.Column(name = "storage_mac_address_2", length = 17)
	public java.lang.String getStorageMacAddress_2() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>cloud.host.storage_netmask_2</code>. 
	 */
	public void setStorageNetmask_2(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>cloud.host.storage_netmask_2</code>. 
	 */
	@javax.persistence.Column(name = "storage_netmask_2", length = 15)
	public java.lang.String getStorageNetmask_2() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>cloud.host.cluster_id</code>. foreign key to cluster
	 */
	public void setClusterId(java.lang.Long value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>cloud.host.cluster_id</code>. foreign key to cluster
	 */
	@javax.persistence.Column(name = "cluster_id", precision = 20)
	public java.lang.Long getClusterId() {
		return (java.lang.Long) getValue(14);
	}

	/**
	 * Setter for <code>cloud.host.public_ip_address</code>. 
	 */
	public void setPublicIpAddress(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>cloud.host.public_ip_address</code>. 
	 */
	@javax.persistence.Column(name = "public_ip_address", length = 40)
	public java.lang.String getPublicIpAddress() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>cloud.host.public_netmask</code>. 
	 */
	public void setPublicNetmask(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>cloud.host.public_netmask</code>. 
	 */
	@javax.persistence.Column(name = "public_netmask", length = 15)
	public java.lang.String getPublicNetmask() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>cloud.host.public_mac_address</code>. 
	 */
	public void setPublicMacAddress(java.lang.String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>cloud.host.public_mac_address</code>. 
	 */
	@javax.persistence.Column(name = "public_mac_address", length = 17)
	public java.lang.String getPublicMacAddress() {
		return (java.lang.String) getValue(17);
	}

	/**
	 * Setter for <code>cloud.host.proxy_port</code>. 
	 */
	public void setProxyPort(java.lang.Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>cloud.host.proxy_port</code>. 
	 */
	@javax.persistence.Column(name = "proxy_port", precision = 10)
	public java.lang.Integer getProxyPort() {
		return (java.lang.Integer) getValue(18);
	}

	/**
	 * Setter for <code>cloud.host.data_center_id</code>. 
	 */
	public void setDataCenterId(java.lang.Long value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>cloud.host.data_center_id</code>. 
	 */
	@javax.persistence.Column(name = "data_center_id", nullable = false, precision = 20)
	public java.lang.Long getDataCenterId() {
		return (java.lang.Long) getValue(19);
	}

	/**
	 * Setter for <code>cloud.host.pod_id</code>. 
	 */
	public void setPodId(java.lang.Long value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>cloud.host.pod_id</code>. 
	 */
	@javax.persistence.Column(name = "pod_id", precision = 20)
	public java.lang.Long getPodId() {
		return (java.lang.Long) getValue(20);
	}

	/**
	 * Setter for <code>cloud.host.cpus</code>. 
	 */
	public void setCpus(java.lang.Integer value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>cloud.host.cpus</code>. 
	 */
	@javax.persistence.Column(name = "cpus", precision = 10)
	public java.lang.Integer getCpus() {
		return (java.lang.Integer) getValue(21);
	}

	/**
	 * Setter for <code>cloud.host.speed</code>. 
	 */
	public void setSpeed(java.lang.Integer value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>cloud.host.speed</code>. 
	 */
	@javax.persistence.Column(name = "speed", precision = 10)
	public java.lang.Integer getSpeed() {
		return (java.lang.Integer) getValue(22);
	}

	/**
	 * Setter for <code>cloud.host.url</code>. iqn for the servers
	 */
	public void setUrl(java.lang.String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>cloud.host.url</code>. iqn for the servers
	 */
	@javax.persistence.Column(name = "url", length = 255)
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(23);
	}

	/**
	 * Setter for <code>cloud.host.fs_type</code>. 
	 */
	public void setFsType(java.lang.String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>cloud.host.fs_type</code>. 
	 */
	@javax.persistence.Column(name = "fs_type", length = 32)
	public java.lang.String getFsType() {
		return (java.lang.String) getValue(24);
	}

	/**
	 * Setter for <code>cloud.host.hypervisor_type</code>. hypervisor type, can be NONE for storage
	 */
	public void setHypervisorType(java.lang.String value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>cloud.host.hypervisor_type</code>. hypervisor type, can be NONE for storage
	 */
	@javax.persistence.Column(name = "hypervisor_type", length = 32)
	public java.lang.String getHypervisorType() {
		return (java.lang.String) getValue(25);
	}

	/**
	 * Setter for <code>cloud.host.hypervisor_version</code>. hypervisor version
	 */
	public void setHypervisorVersion(java.lang.String value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>cloud.host.hypervisor_version</code>. hypervisor version
	 */
	@javax.persistence.Column(name = "hypervisor_version", length = 32)
	public java.lang.String getHypervisorVersion() {
		return (java.lang.String) getValue(26);
	}

	/**
	 * Setter for <code>cloud.host.ram</code>. 
	 */
	public void setRam(java.lang.Long value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>cloud.host.ram</code>. 
	 */
	@javax.persistence.Column(name = "ram", precision = 20)
	public java.lang.Long getRam() {
		return (java.lang.Long) getValue(27);
	}

	/**
	 * Setter for <code>cloud.host.resource</code>. If it is a local resource, this is the class name
	 */
	public void setResource(java.lang.String value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>cloud.host.resource</code>. If it is a local resource, this is the class name
	 */
	@javax.persistence.Column(name = "resource", length = 255)
	public java.lang.String getResource() {
		return (java.lang.String) getValue(28);
	}

	/**
	 * Setter for <code>cloud.host.version</code>. 
	 */
	public void setVersion(java.lang.String value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>cloud.host.version</code>. 
	 */
	@javax.persistence.Column(name = "version", nullable = false, length = 40)
	public java.lang.String getVersion() {
		return (java.lang.String) getValue(29);
	}

	/**
	 * Setter for <code>cloud.host.parent</code>. parent path for the storage server
	 */
	public void setParent(java.lang.String value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>cloud.host.parent</code>. parent path for the storage server
	 */
	@javax.persistence.Column(name = "parent", length = 255)
	public java.lang.String getParent() {
		return (java.lang.String) getValue(30);
	}

	/**
	 * Setter for <code>cloud.host.total_size</code>. TotalSize
	 */
	public void setTotalSize(java.lang.Long value) {
		setValue(31, value);
	}

	/**
	 * Getter for <code>cloud.host.total_size</code>. TotalSize
	 */
	@javax.persistence.Column(name = "total_size", precision = 20)
	public java.lang.Long getTotalSize() {
		return (java.lang.Long) getValue(31);
	}

	/**
	 * Setter for <code>cloud.host.capabilities</code>. host capabilities in comma separated list
	 */
	public void setCapabilities(java.lang.String value) {
		setValue(32, value);
	}

	/**
	 * Getter for <code>cloud.host.capabilities</code>. host capabilities in comma separated list
	 */
	@javax.persistence.Column(name = "capabilities", length = 255)
	public java.lang.String getCapabilities() {
		return (java.lang.String) getValue(32);
	}

	/**
	 * Setter for <code>cloud.host.guid</code>. 
	 */
	public void setGuid(java.lang.String value) {
		setValue(33, value);
	}

	/**
	 * Getter for <code>cloud.host.guid</code>. 
	 */
	@javax.persistence.Column(name = "guid", unique = true, length = 255)
	public java.lang.String getGuid() {
		return (java.lang.String) getValue(33);
	}

	/**
	 * Setter for <code>cloud.host.available</code>. Is this host ready for more resources?
	 */
	public void setAvailable(java.lang.Integer value) {
		setValue(34, value);
	}

	/**
	 * Getter for <code>cloud.host.available</code>. Is this host ready for more resources?
	 */
	@javax.persistence.Column(name = "available", nullable = false, precision = 10)
	public java.lang.Integer getAvailable() {
		return (java.lang.Integer) getValue(34);
	}

	/**
	 * Setter for <code>cloud.host.setup</code>. Is this host already setup?
	 */
	public void setSetup(java.lang.Integer value) {
		setValue(35, value);
	}

	/**
	 * Getter for <code>cloud.host.setup</code>. Is this host already setup?
	 */
	@javax.persistence.Column(name = "setup", nullable = false, precision = 10)
	public java.lang.Integer getSetup() {
		return (java.lang.Integer) getValue(35);
	}

	/**
	 * Setter for <code>cloud.host.dom0_memory</code>. memory used by dom0 for computing and routing servers
	 */
	public void setDom0Memory(java.lang.Long value) {
		setValue(36, value);
	}

	/**
	 * Getter for <code>cloud.host.dom0_memory</code>. memory used by dom0 for computing and routing servers
	 */
	@javax.persistence.Column(name = "dom0_memory", nullable = false, precision = 20)
	public java.lang.Long getDom0Memory() {
		return (java.lang.Long) getValue(36);
	}

	/**
	 * Setter for <code>cloud.host.last_ping</code>. time in seconds from the start of machine of the last ping
	 */
	public void setLastPing(java.lang.Integer value) {
		setValue(37, value);
	}

	/**
	 * Getter for <code>cloud.host.last_ping</code>. time in seconds from the start of machine of the last ping
	 */
	@javax.persistence.Column(name = "last_ping", nullable = false, precision = 10)
	public java.lang.Integer getLastPing() {
		return (java.lang.Integer) getValue(37);
	}

	/**
	 * Setter for <code>cloud.host.mgmt_server_id</code>. ManagementServer this host is connected to.
	 */
	public void setMgmtServerId(java.lang.Long value) {
		setValue(38, value);
	}

	/**
	 * Getter for <code>cloud.host.mgmt_server_id</code>. ManagementServer this host is connected to.
	 */
	@javax.persistence.Column(name = "mgmt_server_id", precision = 20)
	public java.lang.Long getMgmtServerId() {
		return (java.lang.Long) getValue(38);
	}

	/**
	 * Setter for <code>cloud.host.disconnected</code>. Time this was disconnected
	 */
	public void setDisconnected(java.sql.Timestamp value) {
		setValue(39, value);
	}

	/**
	 * Getter for <code>cloud.host.disconnected</code>. Time this was disconnected
	 */
	@javax.persistence.Column(name = "disconnected")
	public java.sql.Timestamp getDisconnected() {
		return (java.sql.Timestamp) getValue(39);
	}

	/**
	 * Setter for <code>cloud.host.created</code>. date the host first signed on
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(40, value);
	}

	/**
	 * Getter for <code>cloud.host.created</code>. date the host first signed on
	 */
	@javax.persistence.Column(name = "created")
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(40);
	}

	/**
	 * Setter for <code>cloud.host.removed</code>. date removed if not null
	 */
	public void setRemoved(java.sql.Timestamp value) {
		setValue(41, value);
	}

	/**
	 * Getter for <code>cloud.host.removed</code>. date removed if not null
	 */
	@javax.persistence.Column(name = "removed")
	public java.sql.Timestamp getRemoved() {
		return (java.sql.Timestamp) getValue(41);
	}

	/**
	 * Setter for <code>cloud.host.update_count</code>. atomic increase count making status update operation atomical
	 */
	public void setUpdateCount(java.lang.Long value) {
		setValue(42, value);
	}

	/**
	 * Getter for <code>cloud.host.update_count</code>. atomic increase count making status update operation atomical
	 */
	@javax.persistence.Column(name = "update_count", nullable = false, precision = 20)
	public java.lang.Long getUpdateCount() {
		return (java.lang.Long) getValue(42);
	}

	/**
	 * Setter for <code>cloud.host.resource_state</code>. Is this host enabled for allocation for new resources
	 */
	public void setResourceState(java.lang.String value) {
		setValue(43, value);
	}

	/**
	 * Getter for <code>cloud.host.resource_state</code>. Is this host enabled for allocation for new resources
	 */
	@javax.persistence.Column(name = "resource_state", nullable = false, length = 32)
	public java.lang.String getResourceState() {
		return (java.lang.String) getValue(43);
	}

	/**
	 * Setter for <code>cloud.host.owner</code>. 
	 */
	public void setOwner(java.lang.String value) {
		setValue(44, value);
	}

	/**
	 * Getter for <code>cloud.host.owner</code>. 
	 */
	@javax.persistence.Column(name = "owner", length = 255)
	public java.lang.String getOwner() {
		return (java.lang.String) getValue(44);
	}

	/**
	 * Setter for <code>cloud.host.lastUpdated</code>. last updated
	 */
	public void setLastupdated(java.sql.Timestamp value) {
		setValue(45, value);
	}

	/**
	 * Getter for <code>cloud.host.lastUpdated</code>. last updated
	 */
	@javax.persistence.Column(name = "lastUpdated")
	public java.sql.Timestamp getLastupdated() {
		return (java.sql.Timestamp) getValue(45);
	}

	/**
	 * Setter for <code>cloud.host.engine_state</code>. the engine state of the zone
	 */
	public void setEngineState(java.lang.String value) {
		setValue(46, value);
	}

	/**
	 * Getter for <code>cloud.host.engine_state</code>. the engine state of the zone
	 */
	@javax.persistence.Column(name = "engine_state", nullable = false, length = 32)
	public java.lang.String getEngineState() {
		return (java.lang.String) getValue(46);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached HostRecord
	 */
	public HostRecord() {
		super(org.apache.cloudstack.db.jooq.tables.Host.HOST);
	}

	/**
	 * Create a detached, initialised HostRecord
	 */
	public HostRecord(java.lang.Long id, java.lang.String name, java.lang.String uuid, java.lang.String status, java.lang.String type, java.lang.String privateIpAddress, java.lang.String privateNetmask, java.lang.String privateMacAddress, java.lang.String storageIpAddress, java.lang.String storageNetmask, java.lang.String storageMacAddress, java.lang.String storageIpAddress_2, java.lang.String storageMacAddress_2, java.lang.String storageNetmask_2, java.lang.Long clusterId, java.lang.String publicIpAddress, java.lang.String publicNetmask, java.lang.String publicMacAddress, java.lang.Integer proxyPort, java.lang.Long dataCenterId, java.lang.Long podId, java.lang.Integer cpus, java.lang.Integer speed, java.lang.String url, java.lang.String fsType, java.lang.String hypervisorType, java.lang.String hypervisorVersion, java.lang.Long ram, java.lang.String resource, java.lang.String version, java.lang.String parent, java.lang.Long totalSize, java.lang.String capabilities, java.lang.String guid, java.lang.Integer available, java.lang.Integer setup, java.lang.Long dom0Memory, java.lang.Integer lastPing, java.lang.Long mgmtServerId, java.sql.Timestamp disconnected, java.sql.Timestamp created, java.sql.Timestamp removed, java.lang.Long updateCount, java.lang.String resourceState, java.lang.String owner, java.sql.Timestamp lastupdated, java.lang.String engineState) {
		super(org.apache.cloudstack.db.jooq.tables.Host.HOST);

		setValue(0, id);
		setValue(1, name);
		setValue(2, uuid);
		setValue(3, status);
		setValue(4, type);
		setValue(5, privateIpAddress);
		setValue(6, privateNetmask);
		setValue(7, privateMacAddress);
		setValue(8, storageIpAddress);
		setValue(9, storageNetmask);
		setValue(10, storageMacAddress);
		setValue(11, storageIpAddress_2);
		setValue(12, storageMacAddress_2);
		setValue(13, storageNetmask_2);
		setValue(14, clusterId);
		setValue(15, publicIpAddress);
		setValue(16, publicNetmask);
		setValue(17, publicMacAddress);
		setValue(18, proxyPort);
		setValue(19, dataCenterId);
		setValue(20, podId);
		setValue(21, cpus);
		setValue(22, speed);
		setValue(23, url);
		setValue(24, fsType);
		setValue(25, hypervisorType);
		setValue(26, hypervisorVersion);
		setValue(27, ram);
		setValue(28, resource);
		setValue(29, version);
		setValue(30, parent);
		setValue(31, totalSize);
		setValue(32, capabilities);
		setValue(33, guid);
		setValue(34, available);
		setValue(35, setup);
		setValue(36, dom0Memory);
		setValue(37, lastPing);
		setValue(38, mgmtServerId);
		setValue(39, disconnected);
		setValue(40, created);
		setValue(41, removed);
		setValue(42, updateCount);
		setValue(43, resourceState);
		setValue(44, owner);
		setValue(45, lastupdated);
		setValue(46, engineState);
	}
}
