/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "ntwk_offering_service_map", schema = "cloud", uniqueConstraints = {
	@javax.persistence.UniqueConstraint(columnNames = {"network_offering_id", "service", "provider"})
})
public class NtwkOfferingServiceMapRecord extends org.jooq.impl.UpdatableRecordImpl<org.apache.cloudstack.db.jooq.tables.records.NtwkOfferingServiceMapRecord> implements org.jooq.Record5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -1006802348;

	/**
	 * Setter for <code>cloud.ntwk_offering_service_map.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cloud.ntwk_offering_service_map.id</code>. 
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 20)
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cloud.ntwk_offering_service_map.network_offering_id</code>. network_offering_id
	 */
	public void setNetworkOfferingId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cloud.ntwk_offering_service_map.network_offering_id</code>. network_offering_id
	 */
	@javax.persistence.Column(name = "network_offering_id", nullable = false, precision = 20)
	public java.lang.Long getNetworkOfferingId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>cloud.ntwk_offering_service_map.service</code>. service
	 */
	public void setService(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cloud.ntwk_offering_service_map.service</code>. service
	 */
	@javax.persistence.Column(name = "service", nullable = false, length = 255)
	public java.lang.String getService() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>cloud.ntwk_offering_service_map.provider</code>. service provider
	 */
	public void setProvider(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cloud.ntwk_offering_service_map.provider</code>. service provider
	 */
	@javax.persistence.Column(name = "provider", length = 255)
	public java.lang.String getProvider() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>cloud.ntwk_offering_service_map.created</code>. date created
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cloud.ntwk_offering_service_map.created</code>. date created
	 */
	@javax.persistence.Column(name = "created")
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.apache.cloudstack.db.jooq.tables.NtwkOfferingServiceMap.NTWK_OFFERING_SERVICE_MAP.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return org.apache.cloudstack.db.jooq.tables.NtwkOfferingServiceMap.NTWK_OFFERING_SERVICE_MAP.NETWORK_OFFERING_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.apache.cloudstack.db.jooq.tables.NtwkOfferingServiceMap.NTWK_OFFERING_SERVICE_MAP.SERVICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.apache.cloudstack.db.jooq.tables.NtwkOfferingServiceMap.NTWK_OFFERING_SERVICE_MAP.PROVIDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return org.apache.cloudstack.db.jooq.tables.NtwkOfferingServiceMap.NTWK_OFFERING_SERVICE_MAP.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getNetworkOfferingId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getService();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getProvider();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreated();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NtwkOfferingServiceMapRecord
	 */
	public NtwkOfferingServiceMapRecord() {
		super(org.apache.cloudstack.db.jooq.tables.NtwkOfferingServiceMap.NTWK_OFFERING_SERVICE_MAP);
	}

	/**
	 * Create a detached, initialised NtwkOfferingServiceMapRecord
	 */
	public NtwkOfferingServiceMapRecord(java.lang.Long id, java.lang.Long networkOfferingId, java.lang.String service, java.lang.String provider, java.sql.Timestamp created) {
		super(org.apache.cloudstack.db.jooq.tables.NtwkOfferingServiceMap.NTWK_OFFERING_SERVICE_MAP);

		setValue(0, id);
		setValue(1, networkOfferingId);
		setValue(2, service);
		setValue(3, provider);
		setValue(4, created);
	}
}
