/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "ovs_tunnel_network", schema = "cloud", uniqueConstraints = {
	@javax.persistence.UniqueConstraint(columnNames = {"from", "to", "network_id"})
})
public class OvsTunnelNetworkRecord extends org.jooq.impl.UpdatableRecordImpl<org.apache.cloudstack.db.jooq.tables.records.OvsTunnelNetworkRecord> implements org.jooq.Record7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 109995747;

	/**
	 * Setter for <code>cloud.ovs_tunnel_network.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cloud.ovs_tunnel_network.id</code>. 
	 */
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 20)
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cloud.ovs_tunnel_network.from</code>. from host id
	 */
	public void setFrom(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cloud.ovs_tunnel_network.from</code>. from host id
	 */
	@javax.persistence.Column(name = "from", nullable = false, precision = 20)
	public java.lang.Long getFrom() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>cloud.ovs_tunnel_network.to</code>. to host id
	 */
	public void setTo(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cloud.ovs_tunnel_network.to</code>. to host id
	 */
	@javax.persistence.Column(name = "to", nullable = false, precision = 20)
	public java.lang.Long getTo() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>cloud.ovs_tunnel_network.network_id</code>. network identifier
	 */
	public void setNetworkId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cloud.ovs_tunnel_network.network_id</code>. network identifier
	 */
	@javax.persistence.Column(name = "network_id", nullable = false, precision = 20)
	public java.lang.Long getNetworkId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>cloud.ovs_tunnel_network.key</code>. gre key
	 */
	public void setKey(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cloud.ovs_tunnel_network.key</code>. gre key
	 */
	@javax.persistence.Column(name = "key", precision = 10)
	public java.lang.Integer getKey() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>cloud.ovs_tunnel_network.port_name</code>. in port on open vswitch
	 */
	public void setPortName(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cloud.ovs_tunnel_network.port_name</code>. in port on open vswitch
	 */
	@javax.persistence.Column(name = "port_name", length = 32)
	public java.lang.String getPortName() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>cloud.ovs_tunnel_network.state</code>. result of tunnel creatation
	 */
	public void setState(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cloud.ovs_tunnel_network.state</code>. result of tunnel creatation
	 */
	@javax.persistence.Column(name = "state", length = 16)
	public java.lang.String getState() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK.FROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK.TO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK.NETWORK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK.PORT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getFrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getTo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getNetworkId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getPortName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getState();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OvsTunnelNetworkRecord
	 */
	public OvsTunnelNetworkRecord() {
		super(org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK);
	}

	/**
	 * Create a detached, initialised OvsTunnelNetworkRecord
	 */
	public OvsTunnelNetworkRecord(java.lang.Long id, java.lang.Long from, java.lang.Long to, java.lang.Long networkId, java.lang.Integer key, java.lang.String portName, java.lang.String state) {
		super(org.apache.cloudstack.db.jooq.tables.OvsTunnelNetwork.OVS_TUNNEL_NETWORK);

		setValue(0, id);
		setValue(1, from);
		setValue(2, to);
		setValue(3, networkId);
		setValue(4, key);
		setValue(5, portName);
		setValue(6, state);
	}
}
