/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "region", schema = "cloud")
public class RegionRecord extends org.jooq.impl.UpdatableRecordImpl<org.apache.cloudstack.db.jooq.tables.records.RegionRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Byte> {

	private static final long serialVersionUID = 1799028729;

	/**
	 * Setter for <code>cloud.region.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cloud.region.id</code>. 
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 10)
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>cloud.region.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cloud.region.name</code>. 
	 */
	@javax.persistence.Column(name = "name", unique = true, nullable = false, length = 255)
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>cloud.region.end_point</code>. 
	 */
	public void setEndPoint(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cloud.region.end_point</code>. 
	 */
	@javax.persistence.Column(name = "end_point", nullable = false, length = 255)
	public java.lang.String getEndPoint() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>cloud.region.portableip_service_enabled</code>. Is Portable IP service enalbed in the Region
	 */
	public void setPortableipServiceEnabled(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cloud.region.portableip_service_enabled</code>. Is Portable IP service enalbed in the Region
	 */
	@javax.persistence.Column(name = "portableip_service_enabled", nullable = false, precision = 3)
	public java.lang.Byte getPortableipServiceEnabled() {
		return (java.lang.Byte) getValue(3);
	}

	/**
	 * Setter for <code>cloud.region.gslb_service_enabled</code>. Is GSLB service enalbed in the Region
	 */
	public void setGslbServiceEnabled(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cloud.region.gslb_service_enabled</code>. Is GSLB service enalbed in the Region
	 */
	@javax.persistence.Column(name = "gslb_service_enabled", nullable = false, precision = 3)
	public java.lang.Byte getGslbServiceEnabled() {
		return (java.lang.Byte) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Byte> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.apache.cloudstack.db.jooq.tables.Region.REGION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.apache.cloudstack.db.jooq.tables.Region.REGION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.apache.cloudstack.db.jooq.tables.Region.REGION.END_POINT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field4() {
		return org.apache.cloudstack.db.jooq.tables.Region.REGION.PORTABLEIP_SERVICE_ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return org.apache.cloudstack.db.jooq.tables.Region.REGION.GSLB_SERVICE_ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEndPoint();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value4() {
		return getPortableipServiceEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getGslbServiceEnabled();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RegionRecord
	 */
	public RegionRecord() {
		super(org.apache.cloudstack.db.jooq.tables.Region.REGION);
	}

	/**
	 * Create a detached, initialised RegionRecord
	 */
	public RegionRecord(java.lang.Integer id, java.lang.String name, java.lang.String endPoint, java.lang.Byte portableipServiceEnabled, java.lang.Byte gslbServiceEnabled) {
		super(org.apache.cloudstack.db.jooq.tables.Region.REGION);

		setValue(0, id);
		setValue(1, name);
		setValue(2, endPoint);
		setValue(3, portableipServiceEnabled);
		setValue(4, gslbServiceEnabled);
	}
}
