/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "system_vm", schema = "cloud")
public class SystemVmRecord extends org.jooq.impl.TableRecordImpl<org.apache.cloudstack.db.jooq.tables.records.SystemVmRecord> implements org.jooq.Record2<java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = 1955916957;

	/**
	 * Setter for <code>cloud.system_vm.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cloud.system_vm.id</code>. 
	 */
	@javax.persistence.Column(name = "id", nullable = false, precision = 19)
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cloud.system_vm.role</code>. 
	 */
	public void setRole(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cloud.system_vm.role</code>. 
	 */
	@javax.persistence.Column(name = "role", nullable = false, length = 1024)
	public java.lang.String getRole() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.apache.cloudstack.db.jooq.tables.SystemVm.SYSTEM_VM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.apache.cloudstack.db.jooq.tables.SystemVm.SYSTEM_VM.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getRole();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SystemVmRecord
	 */
	public SystemVmRecord() {
		super(org.apache.cloudstack.db.jooq.tables.SystemVm.SYSTEM_VM);
	}

	/**
	 * Create a detached, initialised SystemVmRecord
	 */
	public SystemVmRecord(java.lang.Long id, java.lang.String role) {
		super(org.apache.cloudstack.db.jooq.tables.SystemVm.SYSTEM_VM);

		setValue(0, id);
		setValue(1, role);
	}
}
