/**
 * This class is generated by jOOQ
 */
package org.apache.cloudstack.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "user_vm", schema = "cloud")
public class UserVmRecord extends org.jooq.impl.UpdatableRecordImpl<org.apache.cloudstack.db.jooq.tables.records.UserVmRecord> implements org.jooq.Record5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Byte> {

	private static final long serialVersionUID = 484566407;

	/**
	 * Setter for <code>cloud.user_vm.id</code>. 
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cloud.user_vm.id</code>. 
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 20)
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>cloud.user_vm.iso_id</code>. 
	 */
	public void setIsoId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cloud.user_vm.iso_id</code>. 
	 */
	@javax.persistence.Column(name = "iso_id", precision = 20)
	public java.lang.Long getIsoId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>cloud.user_vm.display_name</code>. 
	 */
	public void setDisplayName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cloud.user_vm.display_name</code>. 
	 */
	@javax.persistence.Column(name = "display_name", length = 255)
	public java.lang.String getDisplayName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>cloud.user_vm.user_data</code>. 
	 */
	public void setUserData(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cloud.user_vm.user_data</code>. 
	 */
	@javax.persistence.Column(name = "user_data", length = 16777215)
	public java.lang.String getUserData() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>cloud.user_vm.update_parameters</code>. Defines if the parameters have been updated for the vm
	 */
	public void setUpdateParameters(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cloud.user_vm.update_parameters</code>. Defines if the parameters have been updated for the vm
	 */
	@javax.persistence.Column(name = "update_parameters", nullable = false, precision = 3)
	public java.lang.Byte getUpdateParameters() {
		return (java.lang.Byte) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Byte> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.apache.cloudstack.db.jooq.tables.UserVm.USER_VM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return org.apache.cloudstack.db.jooq.tables.UserVm.USER_VM.ISO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.apache.cloudstack.db.jooq.tables.UserVm.USER_VM.DISPLAY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.apache.cloudstack.db.jooq.tables.UserVm.USER_VM.USER_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return org.apache.cloudstack.db.jooq.tables.UserVm.USER_VM.UPDATE_PARAMETERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getIsoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDisplayName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getUserData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getUpdateParameters();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserVmRecord
	 */
	public UserVmRecord() {
		super(org.apache.cloudstack.db.jooq.tables.UserVm.USER_VM);
	}

	/**
	 * Create a detached, initialised UserVmRecord
	 */
	public UserVmRecord(java.lang.Long id, java.lang.Long isoId, java.lang.String displayName, java.lang.String userData, java.lang.Byte updateParameters) {
		super(org.apache.cloudstack.db.jooq.tables.UserVm.USER_VM);

		setValue(0, id);
		setValue(1, isoId);
		setValue(2, displayName);
		setValue(3, userData);
		setValue(4, updateParameters);
	}
}
